activist-org/activist

frontend/layouts/sidebar.vue
hey @andrewtavis - this is good to go :)
=> #51 Create Sidebar Layout

frontend/components/WebsiteHeader.vue
I tried to fix Header visibility reactive to scrolling.
Please let me know if there is anything that needs to be corrected.
#29
=> update Header visibility reactive to scrolling.

backend/Dockerfile, docker-compose.yml, frontend/Dockerfile
**Description:**
- Updated the docker files to fix path issues to dependencies
- Updated the docker files with some simplification suggestions
----
Also some comments added below for explanations
Cheers :+1:
=> fix: changes to docker files for usability

frontend/nuxt.config.ts, frontend/package.json, frontend/pages/help/contact.vue, frontend/yarn.lock
Following insertions have been made to /help/contact page:
- Added styling for contact page
- Added form with form validation with following rules:
1. Name cant be empty
2. Email needs to be valid (checked with regex)
3. Message cant be empty
What else (ofcourse in my opinion) needs to be done:
- function to send an email
- change text as currently there is Lorem ipsum instead of description
- add toast on succesfully send email
- Maybe styling for disabled button when at least 1 form field is invalid?
Ofcourse i would love to continue to work on that, that's only to verify the conception if its ok. If so then i will be happy to try to add the logic
=> Added contact page styling and form validation

frontend/components/MenuSelector.vue, frontend/components/SearchBar.vue, frontend/components/Sidebar/Sidebar.vue, frontend/components/Sidebar/SidebarFooter.vue, frontend/components/Sidebar/SidebarHeader.vue, frontend/components/Sidebar/SidebarMainSectionSelectors.vue, frontend/pages/home.vue
added `transition-all duration-700` to Sidebar, SidebarFooter,SidebarHeader,SidebarMainSectionSelectors and home
also added flex property to center collapse button
=>  Add transition to sidebar collapse #68 

frontend/assets/css/tailwind.css, frontend/pages/about.vue, frontend/pages/docs/get-active.vue, frontend/pages/docs/get-organized.vue, frontend/pages/docs/grow-organization.vue, frontend/pages/docs/roadmap.vue, frontend/pages/help/contact.vue, frontend/pages/help/faq.vue, frontend/pages/impress.vue, frontend/pages/supporters/index.vue, frontend/pages/supporters/join.vue
- [x ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
Changing the links on activist to be more web accessible.
Changed link elements with tags: 
1. "text-light-cta-orange dark:text-dark-cta-orange hover:underline focus-brand" TO "focus-brand link-text"
2. "items-center text-light-cta-orange dark:text-dark-cta-orange hover:underline focus-brand" TO "items-center focus-brand link-text"
3. Added:
.link-text {
@apply font-bold text-light-special-text dark:text-dark-special-text hover:text-light-text dark:hover:text-dark-text;
}
to the tailwind.css file. 
Total changed files are 11.  They are as follows:
1. frontend/assets/css/tailwind.css
2. frontend/pages/about.vue
3. frontend/pages/docs/get-active.vue …
=> Text link 2

PRIVACY.txt, frontend/pages/legal/privacy-policy.vue
---
This PR adds a detailed privacy policy at /legal/privacy-policy UR
- #44
=> feat: create privacy policy

frontend/components/SearchBar.vue, frontend/yarn.lock
---
Added **" / "** hotkey to the search bar. By clicking the **" / "** button the search bar will be focused.
Also, please describe shortly how you tested that your change actually works --- By running the project on localhost:3000
- #64
=> Added / hotkey in search bar

frontend/components/MeatballMenu.vue
---
- use headlessUI menu and use ref.
- disclosure is not used, I think menu only used is simple.
- The mix of menus and disclosures was difficult to implement for me...
- #49
=> Use ref and use menu instead of disclosure.

frontend/components/Sidebar/SidebarHeader.vue
---
Set the width of the logo to keep it from going small during the transition. Also removed the if statement on the icon to keep it from disappearing.
- #86
=> fixed icon-logo transition

CHANGELOG.md, frontend/components/PopupImage.vue, frontend/pages/docs/get-active.vue, frontend/pages/docs/get-organized.vue, frontend/pages/docs/grow-organization.vue, frontend/tailwind.config.ts
=> #108 Image Popup Feature

CONTRIBUTING.md, README.md
- [ x ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
After the discussion in issue #113, I added a couple sentences recommending that those new to Docker install Docker Desktop to set up their local Development environment. 
- #117
=> feat(documentation): Add information about docker desktop to docs

frontend/components/SearchResult.vue, frontend/pages/home.vue
---
- created search result component added classes to change the layout based on device
- added `card-style flex flex-col sm:flex-row items-center sm:items-start mx-2 my-3` to the base div
- added `w-full sm:w-1/4 bg-light-section-div rounded-md` and `flex flex-col sm:w-3/4 items-center` to the inner shell so that it changes the layout for mobile devices
- #119
=> Add base of 'search result' components #119

frontend/components/TopicMarker.vue
---
Created the topic marker component (TopicMarker.vue).
- Styling is done with Tailwind classes 
- Border, background and text use custom `light-cta-orange` and `dark-cta-orange` colours
- `topic` is passed as a prop to this component to set the text of the marker
Below are screenshots of the component:
- Light mode:
- Dark mode:
- #136
=> feat: Add TopicMarker component (#136)

frontend/components/LandingPage/LandingPageContent.vue, frontend/components/LandingPage/LandingPageSplash.vue
Add h1 and h2 tags for landing page header and section headers 
Issue # 149
These are the header changes that should address the issue
=> header changes(Add h1 and h2 tags for landing page header and section headers )

README.md, frontend/components/MediaMap.vue, frontend/package.json, frontend/yarn.lock
---
1. Added `leaflet`, `@vue-leaflet/leaflet` and `@types/leaflet` dependencies, and updated the `README` to match this.
2. Added the MediaMap component
Below are screenshots of the map:
- Single location/pin:
- Multiple locations/pins:
So currently the MediaMap component takes `addresses` (see below) as a prop (which is an array of strings), formats those addresses and passes them to the `OSM API`, which then returns the latitude and longitude of each location. These are used to display the pins on the map but are also used to calculate average lats and lons between all the addresses for the center point of the map. I realised that this will probably be done in the backend in the future, where the lats and lons will just be directly passed into the frontend, so in the component I …
=> feat: Add media map component (#152)

frontend/components/Cards/CardsSearchResult.vue, frontend/pages/home.vue
Add conditional render on receiving an event prop to display a test event as defined in home.vue
---
Add event search result. Made a small fix in the organization search result where a default image wasn't being displayed properly if it wasn't passed an imageURL.
I also added a conditional icon depending on whether the event is online or in person. The design docs didn't specify this, so let me know if you want this removed :)
I also removed `flex-col` from the parent div so I could get the child div to grow and allow the right-alignment for the location and date-time info. Is this going to break anything down the line, or is there a reason `flex-col` was originally added?
- Closes #121
=> Add event to CardsSearchResult.vue

frontend/components/Grid/CardsMetrics.vue, frontend/components/Grid/GridCardsMetrics.vue
---
Created a requested feature "At a glance metric component" in issue #171. The card component is located in the CardsMetrics.vue file under the grid component directory "frontend/components/grid/" along with the GridCardsMetrics.vue file which is a component with a sample grid using the CardsMetrics component.
I created another vue project in codesandbox.io to develop this feature. It is mostly tailwind.css classes applied to a component so no rigorous testing is required. Here is a link for the sandbox https://codesandbox.io/p/sandbox/lingering-meadow-enxeij?file=%2Fsrc%2Fcomponents%2FCardsMetrics.vue%3A13%2C77. Run "npm run dev" in a new terminal window and view the component in the host window codesandbox creates.
- #171
=> feat(home page): Metrics component initial commit

frontend/components/Card/CardAbout.vue, frontend/package.json, frontend/pages/events/brandenburg-gate-climate-demo.vue, frontend/yarn.lock
---
Added missing elements for CardAbout.vue
-  #128 
- #129
=> Event about component #128

frontend/components/Menu/MenuMobileHeader.vue, frontend/components/SearchBar.vue, frontend/layouts/sidebar.vue
---
- Create MenuMobileHeader component
- Update SearchBarComponent to expand and collapse on click
- #196
=> feat: create MenuMobileHeader component

README.md, backend/requirements.txt
This pull request updates the README.md file and requirements.txt file 
In the `README.md` file, a new section  has been added. This section provides step-by-step instructions on how to install the required Python libraries. It guides users to clone the repository and then install the dependencies using `pip` by running 
`pip install -r requirements.txt`.
The `requirements.txt` file has been updated to include the latest versions of the Python libraries. Each library is listed on a separate line in the format `library_name==version_number`. This ensures that users can easily install the necessary libraries with the correct versions.
These updates aim to enhance the user experience by providing clear instructions on installing the required Python libraries and ensuring that the latest …
=> Updated Documantion

CONTRIBUTING.md, STYLEGUIDE.md
---
- Edit documentation to recommend running `yarn run postinstall` before manually checking types with `yarn nuxi typecheck` in STYLEGUIDE and CONTRIBUTING 
- #216
=> Update documentation to include 'yarn run postinstall' 

frontend/layouts/event.vue
---
Event about page layout; essentially a normal Vue page right now. Open to any suggestions!
Differs slightly from the original design outlined in the #138 but those differences are due to components which were designed differently over the course of the project. Screenshot (in dark mode) below for context:
- #138
=> feat: Add event page layout (#138)

frontend/components/Grid/GridGithubShields.vue, frontend/components/Image/ImageGithubShield.vue
---
1. Fixes `ImageGithubShield`'s prop errors.
2. Refactors `GridGithubShields`'s `<script lang="ts">` to `<script setup lang="ts">`. Follows recommendations from Vue namely changing from [Options API](https://vuejs.org/api/options-state.html) to [Composition API](https://vuejs.org/api/composition-api-setup.html).
- #236
=> Fix: TS errors of ImageGithubShield and refactor GridGithubShields

frontend/components/WebsiteFooter.vue
---
Made changes in `WebsiteFooter.vue` that decrease the size of the footer on small screens. 
Responsiveness tested with dev tools in the browser.
- #244
=> Responsive footer

frontend/components/PageBreadcrumbs.vue, frontend/pages/events/brandenburg-gate-climate-demo.vue, frontend/pages/events/index.vue, frontend/pages/organizations/index.vue, frontend/pages/organizations/tech-from-below.vue
---
This PR adds a directory breadcrumb component to the top of the pages.
- `/components/PageBreadcrumbs.vue` is created and added.
- This breadcrumb component is added into `/pages/events/index.vue`, `/pages/events/brandenburg-gate-climate-demo.vue`, `/pages/organizations/index.vue`, `/pages/organizations/tech-from-below.vue`.
- When backend is integrated, this component needs to add in the function where it parses the url's event/organization ID for the real name.
- #239
=> Feature: directory breadcrumb component

frontend/components/WebsiteHeader.vue
---
I have changed `WebsiteHeader.vue` from the Options API to Composition API. I have also removed two types from `handleScroll` as TypeScript will infer these. 
I tested on localhost:3000 using `docker-compose-up`.
- #237 .5
=> `Header`: Refactor to use Composition API

frontend/components/footer/Footer.vue, frontend/components/landing/LandingCommunityBanner.vue
---
As indicated by the commit [7875c8f](https://github.com/activist-org/activist/commit/7875c8f1c410c1de2a300d1f8ca0cc3be7676191) and discussion in https://github.com/activist-org/activist/issues/244#issuecomment-1656811749, should Twitter be removed from the Connect section of the footer?
#264
=> enhancement- Remove Twitter from the footer and community banner

frontend/components/card/CardTextEntry.vue
---
This PR contains the `CardTextEntry` component. I used the `<h3>` header as the label for the textarea/input field. 
I tested the url  `/en/organizations/1/about` on Chrome, Firefox and Edge. 
- #271
=> CardTextEntry added

frontend/components/footer/Footer.vue, frontend/components/sidebar/left/SidebarLeft.vue
=> condition_classes_applied

backend/apps/models.py
Improved backend/apps/models.py
---
- Every field without a default value has been temporarily set to null=True.
- Fields "creation_date" and "last_updated" have been standardized so that Django manages them automatically:
creation_date = models.DateTimeField(auto_now_add=True)
last_updated = models.DateTimeField(auto_now=True)
- I added a brief comment as a reminder in models.py
- #174
=> improved backend/apps/models.py

backend/authentication/models.py, backend/content/models.py, backend/entities/models.py, backend/events/models.py
---
I tried to reorder the models as suggested, but in some cases, it wasn't possible because the sequence was enforced. I also added an index at the beginning of each module; I believe this, combined with the 'follow-the-references' approach, should make the code readability sufficiently clear. Let me know if you think it can be further improved!
- #322
=> fixed models sequence

CONTRIBUTING.md, frontend/components/media/MediaImageCarousel.vue
Resolves #328 
Standardize props for swiper container
Correct Typo in CONTRIBUTING.md
Original issue #328
---
In #328, it was requested to standardize props in components to match camelCase as opposed to kebab-case - this has been done on one component that has been pointed out.
There was also a typo correction in the CONTRIBUTING.md file (upsteam -> upstream)
- #328
=> Standardize props

backend/authentication/admin.py, backend/authentication/models.py, backend/authentication/serializers.py, backend/backend/settings.py, backend/content/models.py, backend/entities/admin.py, backend/entities/models.py, backend/entities/serializers.py, backend/entities/views.py, backend/events/models.py, backend/events/serializers.py, backend/manage.py
---
This PR adds type annotations to the python backend. It solves the current errors from running mypy.
I ran mypy till there were no errors anymore:
`Success: no issues found in 42 source files`
Additional: i ran the `docker-compose up --build` to check if build works as expected.
- #329
=> Type hints / mypy errors

frontend/components/sidebar/left/SidebarLeftFooter.vue
---
`SidebarLeftFooter` now has props data for its various selectors, for easier maintenance and improvements in the future. 
- #374
=> Refactor: SidebarLeftFooter has better maintainability and readability

docker-compose.yml
=> fix(docker-compose): accept .env backend port on docker-compose.yml

frontend/components/grid/GridGitHubContributors.vue, frontend/i18n/en-US.json, frontend/pages/supporters/index.vue
---
Created `GridGitHubContributors` component which fetches and displays full list of our GitHub contributors, including their avatar images, their log-in IDs, and links externally to their GitHub profile page.
- #231
=> Feature: created GridGitHubContributors custom component

.github/workflows/pr_backend_formatting_check.yaml, backend/authentication/serializers.py, backend/backend/urls.py, backend/content/serializers.py, backend/entities/serializers.py, backend/events/serializers.py
---
In this PR i fixed the current errors shown by running [ruff](https://github.com/astral-sh/ruff) and a workflow for ruff has been added.
I could not test the workflow properly with [act](https://github.com/nektos/act), guess we will have to wait for a PR to see it in action. I do have a similar setup for another project so i assume it should work fine.
- #337
=> fixing ruff errors

frontend/components/grid/GridSearchTags.vue, frontend/pages/events/search.vue, frontend/pages/organizations/search.vue, frontend/pages/search/index.vue
=> #399 Add search tags component

frontend/i18n/en-US.json, frontend/pages/help/contact.vue
---
In this PR i added a subject line to the contact form `en/help/contact`. I have tested thefunctionality with a [free smtp server for testing](https://www.wpoven.com/tools/free-smtp-server-for-testing) 
- #34
=> adding subject line

frontend/components/Media/Calendar.vue
---
It solves the following prettier issue
- It could be related to https://github.com/activist-org/activist/issues/169
=> fix: solve prettier issue in calendar component

frontend/components/selector/SelectorTopBar.vue, frontend/pages/events/[id]/settings.vue, frontend/pages/organizations/[id]/settings.vue
---
SelectorTopBar.vue was added, the file has a for loop, which checks for available top bar elements to display in organisation settings and event settings page.  "SelectorTopBar" tag was added to organisation settings file and event settings file accordingly.
- #398
=> #398 Add selector top bar

frontend/.eslintrc.js, frontend/package.json
=> Enforce order of Vue SFC

CONTRIBUTING.md
---
In this PR i have added a note to the contributing guide for pre-commit as mentioned in #407. 
@andrewtavis let me know if you want me to add the same paragraph to the readme file as well. I checked but i thought it does not fit the "Environment Setup". But i could add it after 4 or 5.
- #412
=> Adding pre-commit to the contributing guide

frontend/components/ProgressBar.vue
- Adds Progress Bar component as per the following design:
- [Figma Design](https://www.figma.com/file/I9McFfaLu1RiiWp5IP3YjE/activist_public_designs?type=design&node-id=2056-3274&mode=design&t=Ny1q4w7M0CBRd5HD-0)
- closes #394
- #ISSUE_NUMBER #394
=> feat(components): Progress Bar

backend/authentication/views.py, backend/backend/paginator.py, backend/backend/settings.py, backend/content/views.py, backend/entities/views.py, backend/events/views.py
---
- #359 
```
page={page_number}
pageSize={data_number}
```
```v1/events/event_attendee_statuses/?page=2&pageSize=3```
=> feat(views): Implementing pagination on listing endpoints

.vscode/settings.json, frontend/.eslintrc.js
=> BugFix: Eslint rules does not gives warning for VS Code

frontend/components/form/FormTextField.vue, frontend/components/tooltip/TooltipPassword.vue, frontend/composables/usePasswordRules.ts, frontend/i18n/en-US.json, frontend/pages/auth/sign-up.vue, frontend/types/password-rules.d.ts, frontend/utils/passwordRules.ts
=> Created a password tooltip component

frontend/components/card/search-result/CardDiscussionEntry.vue, frontend/components/card/search-result/CardSearchResult.vue, frontend/pages/home/index.vue, frontend/types/discussion.d.ts
---
---
created card discussion component as closely as possible to the design . Please let me know if anything needs to be changed. And thanks for your guidance for hacktoberfest.
#463
=> card discussion component

backend/fixtures/superuser.json, docker-compose.yml
---
This PR introduces a fixture for a superuser in the Django backend. The superuser is read from the docker-compose file, enabling access to the Django admin panel without the need to execute` python manage.py createsuperuser` each time.
```
user: admin
pw: admin
```
This will improves the developer experience. 
I executed docker-compose up --build to ensure the changes are valid and the user and pw combination works.
- #491
=> fixture superuser added / load fixture in docker

frontend/package.json
---
- Move `uuid` package to `dependencies`
- related issue https://github.com/activist-org/activist/issues/260#issuecomment-1732129561
=> chore: move uuid to dependecy

frontend/components/card/CardLegalDisclaimer.vue
---
- The component now uses HeadlessUI to manage state and A11Y
- Fixed small issue with text in dark theme
- #498
=> chore: refactor component with HeadlessUI

frontend/components/QRCode.vue, frontend/components/modal/ModalQRCode.vue, frontend/package.json, frontend/yarn.lock
---
This pull request is for separate QRCode in a new component and add the logic necessary to make the button download work. To test it, just press the download buttom in the QRCodeModal.
- #472
=> download-qrcode: new qrcode component and download

frontend/components/btn/BtnLabeled.vue, frontend/components/card/CardConnect.vue, frontend/components/card/CardGetInvolved.vue, frontend/components/form/FormSearch.vue, frontend/components/form/FormTextField.vue, frontend/components/form/checkbox/FormCheckbox.vue, frontend/components/form/checkbox/FormCheckboxBtn.vue, frontend/components/form/radio/FormRadio.vue, frontend/components/form/radio/FormRadioBtn.vue, frontend/composables/useFormCheckboxRadio.ts, frontend/composables/usePasswordRules.ts, frontend/pages/auth/sign-up.vue
=> Bug: Fixing TS errors

.github/workflows/pr_ci_backend.yaml, .pre-commit-config.yaml, backend/pyproject.toml, backend/requirements-dev.in, backend/requirements-dev.txt
---
In this PR, I made adjustments to switch the backend python formatter from black to ruff. I also updated all pre-commit hooks to the newest version. 
To test ruff format I ran the command `ruff format .` in the backend directory. No files have been changed, so I made a mess and checked again. Its compatiably with our current formatting (black) and works as intended.
- #514
=> Ruff formatter

backend/pyproject.toml
---
I added configuration for the coverage report to exclude certain files and directories.
```toml
[tool.coverage.run]
omit = [
"*/migrations/*",
"*/tests/*",
"tests.py",
"asgi.py",
"wsgi.py",
"manage.py"
]
```
- #432
=> config for coverage.py

CONTRIBUTING.md, README.md
---
- Add notes on using SSH keys in setup guide
- Update some stale links to GitHub docs, specifically to
- https://docs.github.com/en/get-started/quickstart/fork-a-repo
- https://docs.github.com/en/get-started/quickstart/github-flow
- #420 :herb:
=> docs: Add notes on using SSH keys in setup guide

.github/workflows/pr_ci_backend.yaml
---
The mypy workflow did not point to the new config file (pyproject.toml). I adjusted the workflow to account for the changes made in #516.
- #513
=> point mypy to the new config file

frontend/components/menu/MenuNavigationDropdown.vue, frontend/layouts/sidebar.vue
=> #279 feature/ManuNavigationDropdown component

backend/events/factory.py, backend/events/tests.py
---
- This PR creates a new file on events for factories and added tests for events
- #509
=> Create factories and tests for events

frontend/components/form/checkbox/FormCheckboxBtn.vue
=> Resolves #453 - Updated FormCheckboxBtn.vue with hover

frontend/components/card/search-result/CardSearchResult.vue, frontend/components/card/search-result/CardSearchResultEvent.vue, frontend/components/card/search-result/CardSearchResultOrganization.vue, frontend/components/card/search-result/CardSearchResultResource.vue, frontend/components/card/search-result/CardSearchResultUser.vue, frontend/pages/organizations/[id]/events.vue, frontend/pages/organizations/[id]/groups.vue, frontend/pages/organizations/[id]/resources.vue
---
Add reduced prop to CardSearchResult to conditionally render search results compacted
Notee: there's seem the be a bug with the date props. Even though they are marked as optional in the TS definition files, if they are not defined the component will break and not render.
- #601
=> Add reduced prop to CardSearchResult to conditionally render search results compacted

frontend/assets/css/tailwind.css, frontend/components/card/search-result/CardSearchResultEvent.vue, frontend/components/card/search-result/CardSearchResultOrganization.vue, frontend/components/card/search-result/CardSearchResultResource.vue, frontend/components/card/search-result/CardSearchResultUser.vue, frontend/components/menu/MenuSearchResult.vue
=> issue #611 fixed

frontend/components/header/HeaderMobile.vue
=> removed fading from mobile header

frontend/components/sidebar/left/SidebarLeftFooter.vue, frontend/types/menu-selector.d.ts
---
I removed some of the duplicate code and made the code more reusable.
I tested my change manually.
- NA
=> Remove reuse code from `SidebarLeftFooter`

backend/backend/custom_settings.py, backend/backend/paginator.py, backend/backend/settings.py
useful for having a single source of truth
---
This change is intended to make it easier to modify specific settings without having to search for them throughout the entire project. It's always useful to have a single source of truth in such large projects.
- #683
=> added custom_settings.py

backend/backend/settings.py
---
Just saw that we overwrite the secret_key settings in backend `settings.py`. There is no reason to keep that in here.
No related issue
=> clean secret key overwrite

frontend/components/sidebar/left/SidebarLeftFooter.vue
---
Please see the discussion in [706](https://github.com/activist-org/activist/pull/706)
```bash
Error: components/sidebar/left/SidebarLeftFooter.vue(16,18): error TS7006: Parameter 'el' implicitly has an 'any' type.
Error:  Command failed with exit code 2: vue-tsc --noEmit
```
- #709
=> fix: solves el type check error

frontend/components/FriendlyCaptcha.vue
---
This addresses the theme change on re-routing to certain pages. The issue was related to the friendly-captcha component where instead of checking whether the theme is dark, it would assign it. 
- #725
=> fix: replace assignment with comparison operation

backend/backend/settings.py
---
Initial django logging setup.
Here is a example log (django_backend is the docker container name):
```bash
django_backend  | WARNING 2024-02-29 19:28:50,990 log 10 139925716757304 Not Found: /
django_backend  | WARNING 2024-02-29 19:28:50,990 basehttp 10 139925716757304 "GET / HTTP/1.1" 404 2766
django_backend  | WARNING 2024-02-29 19:28:51,093 log 10 139925716757304 Not Found: /favicon.ico
django_backend  | WARNING 2024-02-29 19:28:51,094 basehttp 10 139925716757304 "GET /favicon.ico HTTP/1.1" 404 2817
```
With the current configuration log level WARNING and above is outputed to the console. 
- #721
=> Add logging configuration to settings.py

frontend/components/SearchBar.vue, frontend/components/header/HeaderMobile.vue, frontend/components/menu/MenuItemLabel.vue, frontend/components/modal/ModalSharePage.vue, frontend/components/sidebar/left/SidebarLeft.vue, frontend/types/location.ts
=> Add-SeachBar-locations-enum

.github/workflows/pr_ci_backend.yaml
---
I replaced pip with uv as the python package manager to install all the dep. in the backend workflow. We can validate the promised performance benefit by comparing the workflow times.
- #737
=> uv python package manager for backend workflow

frontend/components/footer/flex/FooterFlex.vue, frontend/components/footer/flex/FooterFlexCol.vue, frontend/components/landing/LandingCommunityBanner.vue, frontend/components/meta-tag/MetaTagSocialMedia.vue, frontend/components/modal/ModalSharePage.vue
---
- Updated props for MetaTagSocialMedia component
- Used MetaTagSocialMedia in LandingCommunityBanner and Footer
- Updated MetaTagSocialMedia referenced in ModalSharePage
- Double-Checked that current designs are consistent
- #750
=> Use and update MetaTagSocialMedia

frontend/cypress.config.js, frontend/cypress.config.ts, frontend/cypress/e2e/example.cy.ts, frontend/cypress/support/commands.ts, frontend/cypress/support/e2e.ts, frontend/package.json, frontend/yarn.lock
---
Added cypress with a minimal setup and a very minimal example spec. Greetings to @lucianmurmurache 
Sorry, no issue, I guess?
=> setup cypress and minimal e2e test example

frontend/components/dropdown/DropdownBase.vue, frontend/components/sidebar/left/SidebarLeft.vue, frontend/layouts/sidebar.vue, frontend/tailwind.config.ts
---
Make left sidebar accessible via keyboard 
- #338
=> fix: make left sidebar accessible by keyboard

frontend/components/dropdown/DropdownBase.vue
=> feat: remove `transition` wrap to fix focus transition

frontend/components/grid/GridFilterTags.vue, frontend/pages/events/search.vue, frontend/pages/organizations/search.vue
---
Grid Tags that are similar to topics with a11y.
- #556
=> feat: grid filter tags with a11y

frontend/components/modal/ModalSharePage.vue
=> Add Facebook in Modal Share

frontend/components/media/MediaMap.vue
---
The purpose of this merge request is to set the default map directions to walking.
I tested this manually in my local environment and referenced the [Map Libre Documentation](https://maplibre.org/maplibre-gl-directions/#/examples/multiple-profiles) to confirm the color for the route aligns with the by "foot" profile vs driving.
- #673 
- #718
=> #685/feature update default to walking map directions api

backend/authentication/factories.py, backend/authentication/models.py, backend/authentication/serializers.py, backend/authentication/tests.py, backend/authentication/urls.py, backend/authentication/views.py
---
I added the login API incl. the tests for it.
I have tested 3 scenarios:
* successful login
* user exist but invalid password
* user does not exist 
- #432 #719
=> Login API and test

backend/content/admin.py, backend/content/models.py, backend/content/serializers.py, backend/content/urls.py, backend/content/views.py, backend/entities/models.py
---
I added the models in so far, next up are serializers, views and urls.
- #801
=> iso, grouptext and organization_text models added

backend/authentication/models.py, backend/authentication/serializers.py, backend/authentication/tests.py
---
I added the tests for the Signup endpoint. During the testing I fixed a few issues in the model and serializer (e.g. Passwords were not hashed). 
For backend tests in general I would recommend to use the docstring for documenting the scenarios that are tested.
I ran pytest to see if it works correctly. 
I also saw that we have failing throttling tests, that we should look into.
- #432 #736
=> Signup API tests

frontend/components/dropdown/DropdownDateFilter.vue
=> fixed typo: 'Lase week' -> 'Last week'

backend/authentication/models.py, backend/entities/models.py, backend/events/models.py
---
As discussed in the issue and dev. call.
- #846
=> updated schema Misc changes to backend schemas #846

frontend/components/dropdown/DropdownBase.vue, frontend/components/dropdown/DropdownUserOptions.vue, frontend/i18n/en-US.json
---
This PR updates the "Join" button on the home page to "Join activist" and fixes the button resizing issue that appears with the change.
The updates were:
- added new key in en-US.json
- updated DropdownUserOptions to use new key
- included whitespace-nowrap in DropdownBase MenuButton
- #842
=> Sidebar "join" button text change

frontend/pages/events/[id]/index.vue, frontend/pages/organizations/[id]/index.vue
---
Route now changes to about when starting from a smaller breakpoint and moving onto a larger one. Specifically for [pages/organizations/[id]/about](https://github.com/activist-org/activist/blob/main/frontend/pages/organizations/%5Bid%5D/about.vue) and [pages/events/[id]/about](https://github.com/activist-org/activist/blob/main/frontend/pages/events/%5Bid%5D/about.vue). 
-  #858
=> update route when changing from smaller to larger breakpoints

frontend/pages/events/[id]/about.vue, frontend/pages/organizations/[id]/about.vue, frontend/pages/organizations/[id]/groups/[id]/about.vue
---
Text on share button updates based on screen size. 
-  #857
=> Update buttons based on screen size

CHANGELOG.md
---
This was causing a markdownlint error:
```# [Upcoming] activist 0.1.0```
fixed by adding a `#`:
```## [Upcoming] activist 0.1.0```
- N/A
=> markdownlint fix: MD025/single-title/single-h1

backend/authentication/enums.py, backend/entities/models.py
---
In this PR, I have added enums to improve readability. Inside the authentication folder is a new file called `enums.py` that has all the enums from [authentication app/section].
=> authentication enums added

backend/backend/exception_handler.py, backend/backend/settings.py
---
In this PR, I have added a custom logger for API requests. Currently, we are not capturing details of bad requests. With the custom logger, we will log the serializer's response if an exception occurs.
- No Related Issue
=> custom bad request error logs setup

backend/authentication/models.py
---
Solves a problem with user creation. Email was not set due to wrong ordering of positional arguments.
=> fix creation of superuser

backend/authentication/admin.py, backend/entities/serializers.py, docker-compose.yml
---
In this PR, I have added the orginization_text serializer to the orginization serializer as a field. 
=> Organization text

backend/tests/throttle.py, frontend/components/header/HeaderAppPage.vue, frontend/components/modal/edit/about/ModalEditAboutOrganization.vue, frontend/pages/organizations/create.vue, frontend/stores/event.ts, frontend/stores/group.ts, frontend/stores/organization.ts, frontend/types/entities/organization.d.ts
---
PR does the following:
- Org creation now uses the Pinia store
- Other stores like events and groups have their functions
- Increased the throttle rate by a lot as I have been continually being throttled
- 7 not logged in to 20, and 10 logged in to 30
- No issue
=> Switch org creation to Pinia store + structure other stores + throttle increase

frontend/package.json, frontend/tests/page-objects/LandingPage.ts, frontend/tests/specs/landing-page.spec.ts, frontend/yarn.lock
---
- added missing `#` in `"#btn-become-supporter"`
- updated test on Landing Page to check this button (was missing)
- ran Playwright test to confirm passed
=> fix typo in button locator and update test

frontend/components/combobox/ComboboxTopics.vue, frontend/tests/component-objects/TopicsDropdown.ts, frontend/tests/fixtures/page-fixtures.ts, frontend/tests/page-objects/HomePage.ts, frontend/tests/specs/home-page.spec.ts, frontend/tests/specs/landing-page.spec.ts
---
- Added an `id` attribute to top `<div>` element of `ComboboxTopics.vue` for testing.
- Introduced `HomePage` page object
- Introduced `TopicsDropdown` component object
- Updated fixtures and added `home-page.spec.ts` file with initial tests
- Activated the accessibility test for Landing Page and confirmed it passes
- Skipping Home Page accessibility for now so not to block (many failures)
=> Implemented Home Page Object with Topics Dropdown component and tests

README.md
---
Just a plain & simple typo fix.
=> readme: fix a typo (`accessability` -> `accessibility`)

CONTRIBUTING.md
(This only changes documentation)
---
- #998
=> Add yarn version to docs

CONTRIBUTING.md, README.md, frontend/package.json, frontend/yarn.lock
---
This downgrades the chokidar package so it stops opening too many file watchers prevent running nuxt locally on mac as well as consuming too much memory.  I also added commands to run locally with the correct environment file so new contributors don't have to source `.env.dev` every time they have a new terminal session.
- #1021
=> Run yarn locally

backend/entities/models.py, backend/entities/serializers.py, frontend/components/feed/Feed.vue, frontend/composables/useLinkURL.ts, frontend/stores/event.ts, frontend/stores/group.ts, frontend/stores/organization.ts
- [] I have given maintainers the ability to edit this pull request
---
=> Fixes some issues loading data

backend/authentication/admin.py, backend/communities/groups/views.py, backend/communities/organizations/views.py, backend/content/serializers.py, backend/content/views.py, backend/events/views.py, backend/requirements-dev.in, backend/requirements-dev.txt, backend/requirements.txt
---
We have some dependency warnings on the backend, so I ran `pip-compile` commands with `--upgrade` flags to update the backend dependencies. All tests of platform functionality were successful.
- No issue
=> Run pip-compile --upgrade commands to resolve dependency warnings

frontend/components/media/MediaMap.vue, frontend/i18n/en-US.json
---
Change to update the map directions control based on if the user has put any waypoints for the directions or not :)
- #960
=> #960 Label for directions control reacts to if there are directions

backend/authentication/tests.py
Linked Issue: https://github.com/activist-org/activist/issues/1134
This is a missing test for the file: `backend/authentication/models.py` 
As shown in the issue we can see the file contains a missing test to line `29-38`
I have ran the test locally and seems like all test are passing ✅
we can increase the coverage in the `.github/workflows/pr_ci_backend.yaml` as we cover more test file.
If i am missing something please let me know... 😊
Thanks
---
=> backend/authentication/models.py test for 29-38

backend/communities/tests.py
---
This add a missing test for `backend/communities/models.py                         11      2    82%   21, 31`
- #1134
=> missing test coverage for backend/communities/models.py

.pre-commit-config.yaml, backend/utils/utils.py
---
This pull request adds NumPy validation to the backend. Initially, I have added documentation in 1 file for review. If the maintainer approves it, I will expand the documentation further in this pr.
- backend/utils/util.py
- I have done the backend and linting testing for the changes by following below doc. Attached are the screenshot of testing.
- <img width="1157" alt="Screenshot 2025-04-03 at 4 27 30 AM" src="https://github.com/user-attachments/assets/89e85820-1976-4967-96e9-44e94baf8345" />
- <img width="1147" alt="Screenshot 2025-04-03 at 4 28 07 AM" src="https://github.com/user-attachments/assets/0261330d-2290-4942-b113-ef5504646f71" />
- <img width="1153" alt="Screenshot 2025-04-03 at 4 28 22 AM" src="https://github.com/user-attachments/assets/54997149-419d-4e65-abe3-20231db5740 …
=> In progress: initial numpy validation

backend/communities/admin.py, backend/communities/apps.py, backend/content/admin.py, backend/content/apps.py, backend/events/admin.py, backend/events/apps.py, backend/events/factories.py, backend/events/models.py, backend/events/serializers.py, backend/events/tests.py, backend/events/urls.py, backend/events/views.py
---
- This pull request contains documentation of the events folder in the backend. I have tried to keep the documentation concise and clean if there is anything more needed I would be happy to incorporate the changes. 
- Backend/events folder
- I have done the initial backend testing for by following this [doc](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#testing-). Attached are the screenshots of testing
- <img width="1273" alt="Screenshot 2025-04-04 at 8 48 46 PM" src="https://github.com/user-attachments/assets/4682127c-55cb-4278-8ba6-65e3677ff68e" />
- <img width="1268" alt="Screenshot 2025-04-04 at 8 49 10 PM" src="https://github.com/user-attachments/assets/67b94562-7ba2-4240-aa91-346c75429ac3" />
- <img width="1259" alt="Screenshot 2025-04-04 at 8 50 11 PM" …
=> Doc: Added documentation in backend events folder

backend/content/factories.py, backend/content/models.py, backend/content/serializers.py, backend/content/urls.py, backend/content/views.py
---
This pull request contains numpy documentation for the backend content folder. I have tried to keep the documentation as similar as events folder [Doc:events](https://github.com/activist-org/activist/pull/1204). If there are any changes I will be happy to incorporate it.
- Backend/content folder
I have done the backend testing by following this [doc](https://github.com/activist-org/activist/blob/main/CONTRIBUTING.md#testing-). Attached are the screenshots
- [Issue 1198](https://github.com/activist-org/activist/issues/1198)
=> Doc: Added documentation in content

README.md
---
This pull request improves the grammar, clarity, and consistency in the README.md file. Minor changes include punctuation fixes, hyphenation corrections, and improved sentence structure for better readability.
The edits were tested by visually reviewing the rendered Markdown to ensure formatting remains correct.
- N/A (Minor text improvements not tied to an open issue)
=> improve grammar and clarity in README.md file

backend/communities/organizations/views.py
---
The API response examples provided within `@extend_schema` did not show up in the SwaggerUI. I have started with `OrganizationDetailAPIView`.
I manually tested the SwaggerUI frontend and checked if the examples show up.
=> Improve API documentation

frontend/package.json, frontend/yarn.lock
Update maplibre-gl to v5.4.0 and @maplibre/maplibre-gl-directions to v0.8.0
---
Updated maplibre-gl and @maplibre/maplibre-gl-directions package in frontend to newest versions.
- #1150
=> build: Update maplibre-gl and @maplibre/maplibre-gl-directions to newest verions.

backend/communities/organizations/tests/test_org_retrieve.py, backend/communities/organizations/tests/test_org_update_social_links.py, backend/content/factories.py, backend/content/serializers.py, backend/content/tests/test_discussion_create.py, backend/content/tests/test_discussion_list.py, backend/content/tests/test_discussion_retrieve.py, backend/content/tests/test_discussion_update.py, backend/content/views.py
---
DiscussionFactory instances are being created and works fine (to some extent). I have included 3 tests which include create, retrieve and update.
Current problems with these tests:
1. Create: I get an assertion error (as in the pic). 
2. Update: I get an 403 error. I am able to login and get authenticated but I am still unable to update the contents.
As for Retrieve, the discussion instance works and is passing the test. 
- #1132
=> DiscussionFactory Draft

README.md
- [-] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [-] I have run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](CONTRIBUTING.md#testing)
---
This simply adds the missing URL since r/n there's a clickable link but it goes nowhere.
=> README.md: Add missing link to flokinet

.pre-commit-config.yaml
---
Add a new pre-commit check, by running the formatting check through the frontend code.
| Name | Preview |
|--------|--------|
| Run Individual Hooks - Success  |  <img width="650" alt="image" src="https://github.com/user-attachments/assets/9d311a45-9937-4757-9e81-c86f4d4becdf" /> |
| Run Individual Hooks - Failed | <img width="647" alt="image" src="https://github.com/user-attachments/assets/0893e762-c34f-4a55-86d2-f325d1f2a66d" />  | 
- #1274
=> Add format check to pre-commit

backend/communities/groups/tests/test_group_image.py
---
Added clean up after the group image test.
- #1272
=> fix: Clean up for images test

.pre-commit-config.yaml
---
Adds in pre-commit hooks for various formatting and type checking dependencies :)
- #1273
=> Re-add mypy, prettier and eslint pre-commit hooks

backend/authentication/views.py, backend/communities/groups/tests/test_group_delete.py, backend/communities/groups/views.py, backend/communities/organizations/tests/faq/test_org_faq_update.py, backend/communities/organizations/tests/social_link/test_org_social_link_update.py, backend/communities/organizations/tests/test_org_delete.py, backend/communities/organizations/tests/test_org_retrieve.py, backend/communities/organizations/tests/test_org_update.py, backend/communities/organizations/views.py, backend/content/tests/discussion/entry/test_discussion_entry_delete.py, backend/content/tests/discussion/entry/test_discussion_entry_partial_update.py, backend/content/tests/discussion/entry/test_discussion_entry_update.py, backend/content/tests/discussion/test_discussion_delete.py, backend/content/tests/discussion/test_discussion_partial_update.py, backend/content/tests/resource/test_resource_delete.py, backend/content/tests/resource/test_resource_partial_update.py, backend/content/tests/resource/test_resource_update.py, backend/content/views.py, backend/events/tests/test_event_delete.py, backend/events/tests/test_event_update.py, backend/events/views.py
---
1. Updated error messages key to `detail` and ensured all have a period at the end.
2. Updated relevant unit tests to expect `detail` as a key for error messages.
#1300
=> Standardize backend error messages

backend/authentication/factories.py, backend/authentication/tests/test_auth.py, backend/authentication/urls.py, backend/authentication/views.py
---
This PR has a fix for the user deletion within the backend using the API endpoint. This may not be entirely correct and would like other's opinions on this.
- #1308
=> Fix for User Delete funcationality in the backend.

CONTRIBUTING.md, frontend/components/Typography.vue, frontend/components/header/app-page/HeaderAppPage.vue, frontend/test/components/Typography.spec.ts
---
This PR introduces a new Typography component, a flexible and customizable wrapper for text elements. It supports the following:
Variants such as h1–h6, body, caption, subtitle, link, etc., each mapped to semantic HTML tags
Optional props for size, weight, color, align, font, and text transformations like uppercase, capitalize, etc.
Automatic application of Tailwind utility classes based on design system guidelines
Support for text truncation and responsive behavior …
=> chore: create typogrphy component

frontend/components/modal/edit/text/ModalEditTextEvent.vue, frontend/components/modal/edit/text/ModalEditTextGroup.vue, frontend/components/modal/edit/text/ModalEditTextOrganization.vue, frontend/pages/auth/sign-up.vue
=> Fix sign up page

backend/pyproject.toml
---
Added the required python version, It could be run with some version below 3.11 but since 3.11 had major performance improvements, this seems to be a good way to let people know what we are suggestion to be used. 
=> added python required python version to pyproject.toml

backend/authentication/views.py, backend/communities/groups/views.py, backend/communities/organizations/views.py, backend/content/views.py, backend/events/views.py
Fixes #1386 by converting all Django view tuple assignments to lists for consistency
=>  refactor: switch Django view tuple assignments to lists (#1386)

backend/communities/groups/models.py, backend/communities/organizations/models.py, backend/core/management/commands/populate_db.py, backend/events/models.py, frontend/assets/css/tailwind.css, frontend/components/dropdown/DropdownBase.vue, frontend/components/dropdown/DropdownItemsLayout.vue, frontend/components/menu/MenuItemLabel.vue, frontend/components/modal/add/faq-entry/ModalAddFaqEntryEvent.vue, frontend/components/modal/add/faq-entry/ModalAddFaqEntryGroup.vue, frontend/components/modal/add/faq-entry/ModalAddFaqEntryOrganization.vue, frontend/i18n/en-US.json, frontend/i18n/fr.json, frontend/pages/events/[eventId]/faq.vue, frontend/pages/organizations/[orgId]/faq.vue, frontend/pages/organizations/[orgId]/groups/[groupId]/faq.vue, frontend/utils/sidebarUtils.ts
---
This PR finalizes updating and adding FAQs. Note that I split the add FAQ modal as I figured that would make the work in #1411 :) There also are some misc fixes in here like simplifying conditionals.
- #1417
- #815 
- #818
=> #1417 Order FAQ entries for all edits and adds

backend/authentication/admin.py, backend/authentication/factories.py, backend/authentication/models.py, backend/communities/admin.py, backend/communities/groups/factories.py, backend/communities/groups/models.py, backend/communities/organizations/factories.py, backend/communities/organizations/models.py, backend/content/admin.py, backend/content/factories.py, backend/content/models.py, backend/events/admin.py, backend/events/factories.py, backend/events/models.py, backend/events/tests/social_link/test_event_social_link_create.py
---
- updated all entity models to inherit from their base class
- `EventFaq`, `GroupFaq`, `OrganizationFaq`  inherits from`Faq`
- `EventSocialLink`, `GroupSocialLink`, `OrganizationSocialLink`  inherits from `SocialLink`
- #1458
=> updated entities to inherit from their base content models

backend/core/settings.py
---
Secret key is dynamically loaded from environment variables and in settings file which mypy cannot set properly. Set default value. 
=> fix:set default for SECRET_KEY
