activist-org/activist

- frontend/components/LabeledBtn.vue
- frontend/components/LandingPage/LandingPageSplash.vue
- frontend/pages/index.vue
We’re trying to add external link functionality to LabeledBtn.vue. After this is checked some CTAs on the landing page will be changed to link to Tally forms. 
Note that this has been done on GitHub mobile web, and testing will just be via Netlify instances.
> Allow for LabeledBtn to take external URLs

- frontend/pages/supporters/index.vue
- frontend/pages/supporters/join.vue
To reposition the exterior link icon to be on the same baseline as the text I added 
`style="vertical-align: baseline;"`
to the icons. This should solve the issue for the two pages
>  Put exterior link icons on text baseline in /supporters and /supporter/join #70 

- frontend/error.vue
Changed styling for error page as requested in issue #62 including:
- Theme reactivity
- Logo added
- Button stylization
- Error is now displayed right away after encountering an error
Additionally changed few things:
- resize detection for Medium devices (was small)
- added button transition and styling (as LabeledBtn component)
- fixed responsive issues for small devices
> Style changes according to request in issue #62

- docker-compose.yml
**Description:**
- Updated the `docker-compose.yml` to isolate the `node_modules` directory in its own volume
- Hot-reload now works when attaching the frontend code as a volume. The frontend volume won't override the `node_modules` directory
> fix: isolate node_modules for hot-reload in dev container

- frontend/components/MenuSelector.vue
- frontend/components/Sidebar/SidebarFooter.vue
---
Minor css and transition changes to the icons in [SidebarMainSectionSelectors](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarMainSectionSelectors.vue) and [SidebarFooter](https://github.com/activist-org/activist/blob/main/frontend/components/Sidebar/SidebarFooter.vue). 
Not sure exactly what I could do to make the text any more appealing but I basically played around with the delays and fade ins until I got it to a point that looked good. I think in this case simpler is better and making it any fancier might end up looking worse. Happy to take another stab at it if you have any ideas though.
- specified height and changed padding on the sidebar links to stop them from changing sizes when sidebar is selected
- switched size -> class on Icon in …
> edited icon transitions

- frontend/components/MeatballMenu.vue
---
- When we selected option , dropdown list is closed.
- The action is the same as when I click outside.
- I was able to handle it with headless ui only.
> To me my expectation would be that once you choose something the action occurs and the dropdown is closed, but as of now you need to select and then click outside.
- #49
> Close meatball menu #49

- frontend/components/SearchBar.vue
---
1. Add `transition-opacity transition-duration-200` to the hotKeyIndicators `div`
2. modify the existing CSS conditional `.hide` class from `display: none;` to `opacity: 0;`
3. Remove `focus:w-5/6` from parent input as it was causing a slight layout shift during the transition
Before:
After:
Layout Shift:
- #125
> feat: add transition to hidden hotkey indicators

- frontend/nuxt.config.ts
---
For Safari in iOS, The color used for the status bar is the background color by default ([link to short article](https://useyourloaf.com/blog/safari-15-theme-color/), [link to Apple dev forum thread](https://developer.apple.com/forums/thread/683403)). Following the instructions on those links, I added additional meta tags in nuxt.config.ts to include theme-color for the light and dark themes. When running locally on my PC (viewed in Chrome) this addition doesn't change anything (expected behavior). After I open the PR, I'll check the Netlify preview to confirm the effect for Safari in iOS is as expected.  
- #103
> [fix] Make safari ios status bar update with theme change #103

- frontend/components/LabeledBtn.vue
---
Add icon properties to LabeledBtn component #173
I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)
Description
This issue would be to add two properties and their implementations to the [frontend/components/LabeledBtn.vue](https://github.com/activist-org/activist/blob/main/frontend/components/LabeledBtn.vue) component. We want both properties to be optional, with the first being leftIcon and the second being rightIcon. Each takes a string and would thus allow for identifies of icons to be passed to <Icon> components in the name property.
An example of a LabeledBtn with leftIcon as …
> feature: added leftIcon and RightIcon to LabeledBtn component

- CHANGELOG.md
- docker-compose.yml
- frontend/components/Btn/BtnLabeled.vue
- frontend/components/Card/CardGetInvolved.vue
- frontend/components/Card/CardSearchResult.vue
- frontend/nuxt.config.ts
- frontend/pages/home/index.vue
- frontend/types/resource.d.ts
---
Added a hard-coded resource test search result to home. Also updated
the resource typescript definition to include an optional imageURL
seeing as the other cards had that property.
Also make some small tweaks to the other cards on how the icons were
being displayed with secondary information (location, org, attendees,
date, etc) to make them align with the text. Originally, they were 
slightly offset downwards by a few pixels. 
- #122
> Card resource search

- frontend/nuxt.config.ts
- frontend/package.json
- frontend/tsconfig.json
- frontend/yarn.lock
---
Re-open PR #187 after recent changes as per @andrewtavis instructions
**- Added vue-tsc and typescript to dev dependencies**
**- Added typescript option to `nuxt.config` and compiler options to `tsconfig`**
From `activist/frontend` I ran
```shell
yarn add --dev vue-tsc typescript
```
- A new types file was generated inside .nuxt immediately. I added related typescript code in `nuxt.config.ts` and `tsconfig.json` according to the [nuxt3-awesome-starter](https://github.com/viandwi24/nuxt3-awesome-starter/tree/main)
- - Changes to yarn.lock were automated :sweat_smile:
> **NOTE:** If you see this Error:  ERROR Cannot start nuxt: Cannot find module 'vue-tsc/out/proxy'
restart docker, prune all images, and run docker-compose up --build
Exceptions were thrown where props aren't defined in …
> fix(configuration): Update TypeScript configuration

- CONTRIBUTING.md
- STYLEGUIDE.md
---
In CONTRIBUTING 
- Added a  reference for Nuxt and TypeScript
- Added a note recommending manually check types with `yarn nuxi typecheck` before submitting a PR with new code changes within `frontend`
In STYLEGUIDE
- Created a new section outlining the status of TypeScript configuration with the reasoning behind certain choices.
- Provided recommendations and references for using 
- `defineProps` within `<script>` tags. 
- `defineComponent` otherwise.
- Details explaining the reasoning behind using `yarn nuxi typecheck` within the PR process.
- #199
> feat(documentation): add ts notes to styleguide and contributing 

- frontend/components/Image/ImageGithubShield.vue
- frontend/components/LandingPage/LandingPageCommunityBanner.vue
- frontend/components/WebsiteFooter.vue
---
The code changes in this PR modify the handling of social media links to ensure they open in a new tab or window. This way, users can access the linked social media profiles while keeping the original page intact.
- #225
> fix:social links opens in the same tab

- frontend/components/Btn/BtnLabeled.vue
- frontend/components/LandingPage/LandingPageContent.vue
---
Fixes ts prop errors of `BtnLabeled.vue` and `LandingPageContent.vue`:
1. `BtnLabeled.vue`: 
1. changed `alternateText` to be optional, its type to be string only.
2. changed `iconSize` to be correctly typed with `withDefaults()` wrapper function so it is now optional and has a default value.
2. `LandingPageContent.vue`:
1. changed `imageURL` and `altText` to be optional for the top position variant where there is no image.
- #234 
- #233
> Fix: TS prop errors for some components

- frontend/components/card/search-result/CardSearchResult.vue
- frontend/components/card/search-result/CardSearchResultUser.vue
- frontend/pages/home/index.vue
- frontend/types/user.d.ts
Add user search result card per Figma specs
Add user typescript definition
Note that the icon for the user is just the bootstrap person icon. We'll eventually need some icon SVG defined to replace this to keep in style with the other search result cards
---
- #265
> Add user search result card per Figma specs

- frontend/components/card/CardAbout.vue
- frontend/components/card/CardConnect.vue
- frontend/components/card/search-result/CardSearchResultEvent.vue
- frontend/components/card/search-result/CardSearchResultOrganization.vue
- frontend/components/card/search-result/CardSearchResultResource.vue
- frontend/components/card/search-result/CardSearchResultUser.vue
- frontend/components/popup/PopupNewField.vue
- frontend/tsconfig.json
---
Points to review:
1. `tsconfig` included an alias that appeared to be overriding the defaults from nuxt, causing imported types to not be recognized as well as leading to types from inside `node_modules` not being auto-imported. https://nuxt.com/docs/api/configuration/nuxt-config#alias
2. Change `v-if` in `CardAbout` to use `event` and `organization` instead of `aboutType` following the same style as `CardGetInvolved`
3. Added typing for template ref in `PopupNewField` according to https://vuejs.org/guide/typescript/composition-api.html#typing-template-refs (emit is typed now)
4. In each search result component, the specific result ie `User, organization, resource, event` should not be optional
5. In `CardConnect` removed the arrow function from the emit of `@on-cta-clicked` (I don't …
> fix: TS errors in multiple files in components/card.*

- frontend/components/icon/IconOrganizationStatus.vue
- frontend/pages/organizations/[id]/about.vue
---
In this PR the IconOrganizationStatus component was added. The Icon was made with [bootstrap icons](https://icones.js.org/collection/bi). 
The approved icon is a combination of `check-circle` and `check-circle-fill`.
The pending icon is a combination of `exclamation-triangle` and `exclamation-triangle-fill`.
Prop `status` takes a string `'approved' ` or else it's not approved by default.
To test the component i used the url `.../en/organizations/1/about`. I implemented the component in the about section.
- #272
> IconOrganizationStatus component added

- frontend/components/card/CardDangerZone.vue
- frontend/pages/organizations/[id]/about.vue
---
This PR contains the CardDangerZone component. I tested the url `/en/organizations/1/about` and used the chrome devtools to check light/dark mode. 
Comments:
I used the styles from `card-style` for the first `<div>` element without the colors to keep the card consistent with the rest. But it will not be updated in case the `card-style` changes. I think a `base-card-style` without colors could help.
- #274
> CardDangerZone implementation

- STYLEGUIDE.md
- frontend/components/card/CardConnect.vue
- frontend/components/card/CardFeed.vue
- frontend/components/media/MediaMap.vue
- frontend/types/event.d.ts
- frontend/types/organization.d.ts
---
As discussed in #261. 
1. Refactored uses of `Array<T>` to `'arrayElemType'[]` as needed 
2. Removed `[string]` in `event` and `organization` to allow for string arrays `[string]` -> `string[]`
3. TS `STYLEGUIDE`: Removed `<script>` information  and added recommendations for TS and links to relevant docs
- #261
> fix: typescript errors in pages dir, refactor style guide

- frontend/components/PageBreadcrumbs.vue
- frontend/components/landing/LandingContent.vue
- frontend/components/modal/ModalImage.vue
- frontend/components/selector/SelectorLanguage.vue
- frontend/components/sidebar/left/SidebarLeft.vue
- frontend/components/sidebar/left/SidebarLeftFooter.vue
---
Fixes TS errors for several misc components listed as below:
1. `PageBreadcrumbs`
2. `ModalImage`
3. `LandingContent`
4. `SidebarLeft`
5. `SidebarLeftFooter`
6. `SelectorLanguage`
Although now TS errors are all gone, I am not happy about the work-arounds relating i18n's `locales` interface. For example, in `SelectorLanguage`, the original error was about `locales.value.filter` because locales has an union of `string[] | LocaleObject[]`. 
I researched for some time and found only a walkaround as in my PR, and the result is that now the `availableLocales` has a type of `Array<string | LocaleObject>`, so another function `getLocaleCode` is added. 
I don't think this is an elegant solution so maybe you can take a look at it?
- #262
> Fix: fixes TS errors in misc components

- frontend/components/media/MediaImageCarousel.vue
---
`MediaImageCarousel` is now converted to [Swiper Element](https://swiperjs.com/element). And it is now using Vue Composition API as well.
While I used [Parts](https://swiperjs.com/element#parts) to target prev and next buttons for some custom stylings:
```
swiper-container::part(button-prev),
swiper-container::part(button-next) {
@apply focus-brand text-light-cta-orange hover:text-light-cta-orange-hover dark:text-dark-cta-orange dark:hover:text-dark-cta-orange-hover;
}
```
~I **can't** seem to target the **pagination bullets** for more custom CSS styles, I have tried the example but it does not work. I think it might be a bug for Swiper, please give it a spin and let me know if I should submit an issue for them.~
Just as I was writing up this PR, the custom CSS styles for pagination …
> Feature: MediaImageCarousel converted to Swiper Element

- .github/workflows/pr_python_formatting_check.yaml
---
This PR adds a GitHub Action workflow that checks if python code is formatted with black. The workflow targets the `backend` folder and excludes migrations. I have excluded migrations since they are autogenerated by django.
I have tested the black command:
```powershell
black ./backend --check --verbose --exclude "migrations/" 
```
Here is the result:
```
...
would reformat C:\Users\tobia\Documents\Projects\contrib\activist\activist\backend\apps\models.py
Oh no! 💥 💔 💥
1 file would be reformatted, 14 files would be left unchanged.
```
So currently the Github Action should fail because the models.py is not formatted with black.
I tried to test the Github Action locally with [act](https://github.com/nektos/act) but ran into a known [issue](https://github.com/nektos/act/issues/1765) that …
> Added Black formatting Github Action

- .github/workflows/pr_maintainer_checklist.yaml
---
- Add a reference to the `pr_maintainer_checklist` workflow to check the TS error logs.
- #314
> chore: add TS error check reference to pr_maintainer_workflow

- backend/apps/models.py
- docker-compose.yml
---
In this PR the standard model structure was implemented to all models inside `backend/apps/models.py`. 
The `index` for each model was changed to `id` and set as primary key.
```python
index = models.IntegerField(null=True)
id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
```
Timestamps have been grouped and seperated by a blank line on each model. 
Example: 
```python
class Role(models.Model):
id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
name = models.CharField(max_length=255)
is_custom = models.BooleanField(null=True)
description = models.TextField(max_length=500)
creation_date = models.DateTimeField(auto_now_add=True)
last_updated = models.DateTimeField(auto_now=True)
deprecation_date = models.DateField(null=True)
def …
```
> Models standard structure

- .github/workflows/pr_backend_formatting_check.yaml
- .github/workflows/pr_frontend_formatting_check.yaml
---
This PR adds a github workflow to check frontend formatting with [prettier](https://prettier.io/). The workflow file `pr_frontend_formatting_check.yaml` was added. It targets the frontend folder and checks the formatting. Files are not changed but this can be changed in the long run with `dry: False`. 
Similar to #316 i tried to use [act](https://github.com/nektos/act) to run the GitHub action locally but ran into a known issue.
<ins>Additional</ins>:
I standardize the steps inside pr_python_formatting_check.yaml. Minor change that makes the github actions logs more readable. We have to check this with a PR again 😃.
<ins>Suggestions</ins>:
I named the file `pr_frontend_formatting_check` could also be `pr_prettier_formatting_check` (or something else 😄) but i do like the frontend and …
> added frontend formatting check and stand. steps

- frontend/components/Loading.vue
---
When user navigates to a new page, then goes back, and then their view on the original page is lower than it was before.
This was caused because the loading component was not fixed, making the page going down.
To solve this problem I fixed the loading component and setting z-index to be above others components.
- #318
> fixing loading component

- frontend/components/header/HeaderAppPage.vue
- frontend/components/sidebar/left/SidebarLeftFooter.vue
- frontend/nuxt.config.ts
---
1. `SidebarLeftFooter`: fixes tab control order misbehaviour, now pressing enter key on the DisclosureButton will move focus to the first child element in DisclosurePanel.
2. `HeaderAppPage`: fixes TS props error where props `header` and `tagline` was required before, but the normal use case is that either `organization`, or `event`, or `header + tagline` is passed into this component.
3. `nuxt.config.ts`: fixes console error messages about our `swiper-container` and `swiper-slide` custom html elements in `MediaImageCarousel` component. See this [StackOverflow thread](https://stackoverflow.com/questions/71601714/how-to-set-compileroptions-iscustomelement-for-vuejs-3-in-laravel-project). The error messages in console was like this …
> Fix: SidebarLeftFooter tab control order fix and misc fixes

- frontend/components/sidebar/right/SidebarRight.vue
---
According to #321, the [right sidebar](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/right/SidebarRight.vue) for mobile that houses the theme and language selectors doesn't have a transition when toggled. I have added a transition similar to the [left sidebar component](https://github.com/activist-org/activist/blob/main/frontend/components/sidebar/left/SidebarLeft.vue).
- #321
> feat(ui): #321 Add right sidebar transition

- .github/workflows/pr_frontend_formatting_check.yaml
- .gitignore
- .vscode/settings.json
- frontend/.prettierignore
- frontend/.prettierrc
- frontend/package-lock.json
- frontend/package.json
- frontend/yarn.lock
---
This PR is related to the recently merged PR #324. It builds on the GitHub workflow but instead of using a predefined Github Action `creyD/prettier_action@v4.3` we manually install prettier an run it. 
Prettier was installed via npm and configuration files were added. 
I ran a test of prettier and the GitHub workflow with act. Both worked and only [warn] showed up, where most of changes are the end of line sequence from `crlf` to `lf`. Prettier uses `lf` by default, we could overwrite the default in the `.prettierrc`.
```json
"endOfLine": "crlf"
```
I did not run `npx prettier . --write` to make the changes yet.
- #323
> Prettier config and workflow setup

- frontend/layouts/sidebar.vue
---
I resolved the issue with the sidebar blur not appearing over the footer at medium and small view widths. It was a simple fix. I just copied the code that applied blur to the rest of the page and added it to the footer in [frontend/layouts/sidebar.vue](https://github.com/activist-org/activist/blob/main/frontend/layouts/sidebar.vue). I ran a Docker container with the updated code and it seemed to resolve the issue at the desired breakpoints. 
Let me know if there is anything I can do to improve my workflow or communication for future contributions. I'm still very new to open source contributions such as this, and advice is always appreciated. 
- [Issue355
](https://github.com/activist-org/activist/issues/355)
> Fix: Sidebar hover blur now covers footer at md and lg breakpoints

- frontend/pages/events/[id]/index.vue
- frontend/pages/organizations/[id]/index.vue
---
Regarding the /events/[id] and /organizations/[id] pages, I made an improvement for the user experience. Now, when the user views these pages in a window with a width smaller than or equal to 640px and then resizes it to a larger width, I've implemented an event listener to track the size change.
This way, if the user resizes the screen to a width greater than 640px, they will be automatically redirected to the /about page. This ensures a smooth and intuitive transition for the user when they enlarge the window, maintaining the consistency and usability of the website.
- #365
> Redirecting to /about after resizing to a medium device

- backend/authentication/serializers.py
- backend/authentication/views.py
- backend/backend/settings.py
- backend/content/serializers.py
- backend/content/views.py
- backend/entities/serializers.py
- backend/entities/views.py
- backend/events/serializers.py
- backend/events/views.py
- backend/utils/utils.py
---
In this PR i fixed the current errors from running mypy in the backend directory.  Had to make changes in the settings.py file to solve issues that would have occured when running django [with type annotations for ModelViewSets](https://github.com/typeddjango/djangorestframework-stubs/issues/255).
@andrewtavis we talked briefly in the 🌙 Code Night about internationalization and the following function:
```python
def validate_object_existence(model, object_id):
if model.objects.filter(id=object_id).exists():
raise serializers.ValidationError(
_("There is no %(model_name)s object with id %(object_id)s."),
code="inexistent_object",
params={"model_name": model.__name__, "object_id": object_id},
)
def validate_object_existence(model: Any, object_id: Any) -> None:
if …
```
> Solving mypy errors

- CONTRIBUTING.md
- README.md
---
Improving contrig guide and readme adding PR steps 
- #407
> improving contrib guide and readme

- .github/workflows/pr_backend_formatting_check.yaml
- backend/mypy.ini
---
In this PR i have added mypy (Static Type Checking for python) to the backend workflow. This is the last missing piece for the issue #329. 
I tested the cli command locally and then run the workflow via [act](https://github.com/nektos/act).
<ins>Comments:</ins>
While looking into the workflows,  i was thinking that we should rename the files now.  pr_backend_formatting_check does linting and static type checking. I think pr_ci_backend would make sense. I will open an issue for that and a few more minor things regarding workflows.
- #329
> mypy workflow setup

- frontend/components/SearchBar.vue
- frontend/components/tooltip/BaseTooltip.vue
---
Add a BaseTooltip component.
Tested by adding into the search bar component.  I kept the styling classes invisible and mt-8 in the invocation of BaseTooltip in the SearchBar component, since I assume those styling features are specific to its location. I didn't mess with the control and command k tooltips that are commented out because I do not have a mac to test them on.
All other styling fits the designs on Figma except the text-color for dark mode. I could not find the exact color in the stylesheet. I removed the 'Header' placeholder before commiting the changes. Let me know if you need me to change anything or have any concerns!
- #400
> Add BaseTooltip component and update it to the search bar

- .github/workflows/pr_ci_backend.yaml
- .github/workflows/pr_ci_frontend.yaml
- backend/authentication/serializers.py
- backend/content/serializers.py
- backend/entities/serializers.py
- backend/events/serializers.py
---
In this PR, I added the eslint to the frontend check. I also realized that we have added continue-on-error to the frontend check but not to the backend check. That can be seen in the PR #465, where ruff fails due to import sorting and mypy will not be executed anymore.
I tested ran the command in the frontend docker container.
- #446
> eslint workflow added and contine-on-error added

- backend/backend/settings.py
---
This PR solves the bug that breaks the Swagger UI endpoint `/v1/schema/swagger-ui/`. This can be considered  a workaround, since we are reloading the drf api_settings after calling the monkeypatch function.  
There is currently a open issue on djangorestframework-stubs that is related to this bug. Let's keep the issue #471 open to keep track of the changes.
I have tested the endpoint to make sure it works.
- #471
> reload drf api settings to solve Swagger UI bug

- frontend/components/page/PageBreadcrumbs.vue
---
Added a flex-wrap so the li's wrap to the next line when hitting the full width, I tested it by manually adding items in the html. See attached screenshot.
- #475
> added flex-wrap to breadcrumb component so li's go on to the next line

- .github/workflows/pr_ci_backend.yaml
- .github/workflows/pr_ci_frontend.yaml
---
If I'm understanding correctly, I think the trigger event type that we would want is `pull_request` rather than `pull_request_target`. 
From the [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target):
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the `pull_request` event does. 
- #489
> fix(ci): correct event type "pull_request"

- frontend/components/marker/MarkerPrivacy.vue
- frontend/i18n/en-US.json
---
Used a lot of the button code but removed the hover states and all the extra functionality for creating links. I've took some screenshots to show the possible examples. 
>
- #397
> Added privacy marker icon

- frontend/components/form/FormViewSelector.vue
- frontend/i18n/en-US.json
- frontend/types/view-types.ts
---
Added a `FormViewSelector` that is taking `v-model`, `option1`, `option2` as required and `option3` as optional
- [#ISSUE_NUMBER](https://github.com/activist-org/activist/issues/456)
> Added FormViewSelector

- .gitignore
- backend/content/factory.py
- backend/content/tests.py
- backend/mypy.ini
- backend/pyproject.toml
- backend/requirements-dev.in
- backend/requirements-dev.txt
---
In this PR, I added initial tests for the `content` app. The tests check the __str__ method of the models. A base setup for coverage is added to `pyproject.toml`.
In factory.py are all the models to create objects for models that can be used for tests. [factory_boy](https://factoryboy.readthedocs.io/en/stable/) uses the [faker](https://faker.readthedocs.io/en/master/) package to generate fake names, words, and so on. That let's us create tests without the use of fixtures.
<ins>Issues:</ins>
* Currently there is no support for generic types with factory_boy, therefore I excluded the factory.py file and its imports from being checked by mypy.
* I excluded TopicFormat, since it has a ForeignKey to another app (events). There is only a placeholder `TopicFormatFactory` at the moment. We …
> Test setup and first tests inside content app

- frontend/components/SearchBar.vue
---
- Used a custom event handler to hijack what happens when slash is pressed
- Added an if statement around input focus as it was throwing an error even prior to the above change
- #510
> Fixed bug with slash hotkey getting picked up by firefox

- .github/workflows/pr_ci_backend.yaml
- .github/workflows/pr_ci_frontend.yaml
- .github/workflows/pr_maintainer_checklist.yaml
---
Working on #429 , I noticed a couple points in our existing workflows:
- Was wondering if the `Checkout` step was necessary in the `pr_maintainer_checklist.yaml`, since the workflow doesn't perform any steps actually involving the source code. Tried removing this step and tested in my fork:
- Test PR: https://github.com/wkyoshida/activist/pull/1
- Notice in the [logs](https://github.com/wkyoshida/activist/actions/runs/6714205076/job/18247071592) that the workflow does not perform the `Checkout` step and still succeeds :rocket: 
- Also, the `workflow_run` triggers in the `pr_ci_backend.yaml` and the `pr_ci_frontend.yaml` appear to be redundant, since there is already a trigger for when the `pull_request` is `opened`. The `pr_maintainer_checklist` workflow is `completed` mere seconds …
> refac: Remove unnecessary triggers and steps in GitHub Actions

- backend/backend/tests/unit/conftest.py
- backend/backend/tests/unit/test_swagger.py
---
I've created the folder /backend/backend/tests/unit to organize the unit tests.
I also created two files:
1. conftest.py -> to place fixtures that can be reused 
2. test_swagger.py -> containing the test cases for the swagger ui endpoints:
- /v1/schema/
- /v1/schema/swagger-ui/
The tests cases verify if a http request to those endpoints returns a 200 status.
To test if it works I've changed the urls.py file and ran the tests.
- #533
> #533 feat: creating tests for swagger ui

- backend/authentication/factories.py
- backend/authentication/tests.py
- backend/backend/settings.py
- backend/content/factories.py
- backend/content/tests.py
- backend/pyproject.toml
---
- #507
I added a 'DEFAULT_PAGINATION_ORDERS_OBJECTS': False in the REST_FRAMEWORK settings to not require ordering on endpoints where order_by is optional
> #540 Feat(Authentication) create tests and factories in authentication

- frontend/components/card/CardAbout.vue
- frontend/components/meta-tag/MetaTagOrganization.vue
- frontend/pages/events/[id]/about.vue
- frontend/types/event.d.ts
---
On page Events at Card About adding the possibilite to have more than 1 organization.
When I was making the changes I've notice an error in pages/events/[id]/about.vue at line [80](https://github.com/activist-org/activist/blob/51787568ebbb6eb9045b0b172cfc86ae3b68ca79/frontend/pages/events/%5Bid%5D/about.vue#L80C6-L80C6)
the prop social-links was showing: Type 'string[] | undefined' is not assignable to type 'string[]'.
Type 'undefined' is not assignable to type 'string[]'.
I didn't change it because was not the purpose of this issue and someone could already been working on it
- #557
> feat: on events/CardAbout changing organizations to an array of strings 

- docker-compose.yml
- frontend/Dockerfile
---
I believe I may have found an option that addresses the issues we've been seeing with setting up the development environment.
- Removing the `/app/node_modules` volume we were using before to isolate the local `node_modules` and the `node_modules` in the container (they are now the same).
- Moving the `yarn install` and the `yarn dev` to outside the `Dockerfile` and into the `docker-compose.yml` so that the dependency resolution and the types generation happen when the stack starts up, as opposed to when the image is built. 
The two changes above make it so that the latest dependencies and types get resolved simply by starting up the stack, but also "stores" them locally. 
P.S.
- Retrospective - the previous setup was used to isolate the volume, since the `node_modules` in the …
> dev: Resolve dependencies & generate types when compose starts up

- frontend/components/card/discussion/CardDiscussionInput.vue
- frontend/i18n/en-US.json
- frontend/pages/events/[id]/discussion.vue
- frontend/types/card-discussion-input.d.ts
---
**Description**
This pull request introduces the isHighRisk property to the CardDiscussionInput component in the activist project. The feature aims to increase safety for users who are part of or interacting with high-risk organizations. It modifies the user interface to display warnings and different styles when the isHighRisk flag is true.
**Testing**
The feature was tested in a local development environment. The UI changes were verified for both high-risk and non-high-risk scenarios. Additionally, the feature was tested in dark mode to ensure visual consistency and accessibility
**Proof of output:**
_Light Mode:_
_Dark Mode:_
**Issue Number**
This pull request Closes Issue #558: ["Add isHighRisk prop to CardDiscussionInput"](https://github.com/activist-org/activist/issues/558), …
> Implemented the isHighRisk Component to Activist

- frontend/components/card/CardDatePicker.vue
---
This PR comes to resolve a coloration problem that ocurred after we clicked in a day on the calendar
- #559
> resolving coloration problem

- docker-compose.yml
---
Coming out of the [discussion](https://matrix.to/#/!CRgLpGeOBNwxYCtqmK:matrix.org/$5OLIJ-4DHZHS4U3DrDfkHrfkunWkiCsdEV9IcTxBInI?via=matrix.org&via=acter.global&via=chat.0x7cd.xyz) in the Matrix, decided to look into why trying to set a different front-end port was not working. Seems that we were missing configuring it in the command when starting up the stack. 
Before, `FRONTEND_PORT` was only being used for exposing the container ports.
- N/A
> fix(dev): Add FRONTEND_PORT env to configure port on compose

- frontend/components/menu/MenuSearchResult.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultEvent.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultOrganization.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultResource.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultUser.vue
- frontend/composables/useTabNavigationEmit.ts
- Added 'onTab' function in MenuSearchResult.vue to close the tooltip when the Tab key is pressed on the last element.
---
- #608
> #608. Create 'onTab' Function for Tooltip Visibility Control

- backend/content/factories.py
- backend/content/models.py
- backend/content/serializers.py
- backend/content/views.py
---
In this PR, I have started implementing the first API for the Resource table. I had to make some changes to the table in order to make the privat field useful. I added the created_by to implement the logic for GET requests. 
In case a user is the creator for a resource and the privat field is set to True, the creator should still be able to retrieve the resource. Permissions are set to `IsAuthenticatedOrReadOnly`. 
Additionally, I have deleted a few validation utility functions inside the serializer, because the model itself already provided sufficient validation.
`GET, POST, PUT, PATCH` methods are setup with the viewset methods. I used the  
Tests have been manually via swagger for all the methods and endpoints that are covered by the ResourceViewSet. I would suggest to create unit …
> Initial Resource API setup 🎅🎁🎄 

- frontend/components/combobox/ComboboxTopics.vue
- frontend/package.json
- frontend/yarn.lock
---
Fixes Issue #618. Tabbing into the combo box will now have the same functionality as clicking into it. The second commit is just adding comments.
- #618
> Combobox options expand on tab

- CONTRIBUTING.md
- README.md
---
Add documentation on splitting front and back-end environments. ### Using Yarn or Python section added
to CONTRIBUTING.md at line 200. Link to this section added to README..md at line 192.
Made sure the link properly moves user to correct section.
- #617
> added directions on split dev environment

- frontend/components/menu/MenuSearchResult.vue
---
This pull request fixed the MenuSearchResult tooltip functionality. Previously, it would not close on menu button click due to an `onClickOutside` event firing, therefore preventing `showTooltip` from being set to false in the menu button click. 
This was solved by reassigning  the `tooltip` reference to the `div` of the menu button and tooltip components. This will allow the `onClickOutside` function to correctly handle the visibility of these components appearing. 
I additionally added a `toggleToolTip` function for future readability/debugging purposes. Finally, I removed the `tooltip` references from the TooltipMenuSearchResult components themselves, as the `tooltip` reference is now handled by the parent div. 
I tested this by logging the value of the `showTooltip`, and it now …
> Fix: Menu tooltip close fix

- frontend/components/card/CardAbout.vue
---
This PR is related to https://github.com/activist-org/activist/issues/658 issue.
I tested it manually.
- #658
> Disable CardAbout expand text functionality if text doesn't trigger line clamp

- frontend/components/card/CardTopicSelection.vue
- frontend/components/form/checkbox/FormCheckbox.vue
---
This should allow the selection of topics to loop while navigating using arrow keys.
This PR also fixes the problem where tabbing will go to the next component instead of a fixed component.
- #527
> feat: topics loop selection and tabbing A11y

- frontend/nuxt.config.ts
- frontend/plugins/i18n-head.ts
---
This addresses the missing lang attribute to the html element for all pages.
The attribute is injected via a plugin created under `/plugins/i18n-head.ts`
- #703
> Add html lang attribute

- frontend/components/sidebar/right/SidebarRight.vue
- frontend/i18n/en-US.json
---
SidebarRight is not closing when an option is selected. This can be seed from the mobile view on any page where the burger menu is used to open the sidebar, and then once a new localization, color mode or another option is selected the sidebar is still open. 
❗ Should check UX flow if the desired behaviour above is correct. For now the fix only addresses click/press outside the menu
- #711
> fix: closes menu on click outside

- frontend/components/sidebar/left/SidebarLeftHeader.vue
- frontend/components/sidebar/right/SidebarRightToggle.vue
---
Currently we are replacing the icon based on the open/close state for both left and right sidebars. Instead, this approach will avoid the icon re-render while at the same time, add a little animation. The left sidebar icon will be rotated -180deg while the right icon will be rotated 180deg to keep the animations consistent.
- #729
> chore: add animation to sidebar icon on toggle

- frontend/components/footer/flex/FooterFlex.vue
- frontend/components/footer/flex/FooterFlexCol.vue
- frontend/i18n/en-US.json
---
Change the footer year based on current year.
- #726
> fix: make footer copyright year dynamic

- frontend/components/sidebar/right/SidebarRight.vue
---
This addresses the discussion/decision to close the sidebar when the language option is selected (route change). This approach I decided on, would entail the least amount of changes, simply watching for route changes and then triggering the close function. 
- #711
> fix: close sidebar on route change

- frontend/components/header/HeaderAppPage.vue
- frontend/components/header/HeaderMobile.vue
- frontend/components/header/HeaderWebsite.vue
- frontend/components/menu/MenuNavigationDropdown.vue
---
The right sidebar is overlapped by the navigation menu.
The use of relative and sticky in the same line.
"This page is currently under development" message does not look right on sm & md screens
- #752
> style: address a few inconsistencies

- frontend/assets/css/tailwind.css
---
This is both a slight UX imprvement and a fix for the issue mentioned below. Focus styles are generally not required when the user knows where they are focusing on, meaning if they use a touch screen or a mouse, it's not necessary to show the focus ring on the element you just pressed/clicked (a few exceptions, such as inputs), it is however absolutely necessary when using a keyboard. `focus-visible` is a viable replacement. Now we have a slightly cleaner design for users that use the mouse, and we still show a focus for things like inputs and textareas. A more detailed explanation can be found on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
- #644
> style: replace focus with focus-visible

- frontend/components/media/MediaMap.vue
---
Adds the `cursor-pointer` class to the marker that is being added to the map.
- #684 
Although the marker now shows a pointer, and clicking the marker shows the expected popup, it also starts the routing (nice feature, btw!). For me that seems odd and probably unintentional.
> feat: show pointer cursor on map marker hover

- frontend/components/media/MediaMap.vue
---
Added two event listeners to the MediaMap.vue file, one that disables directions interactivity when entering the marker, and one enabling it when leaving the marker.
- #767
> #767/Added event disabling interaction on map marker.

- frontend/components/media/MediaMap.vue
---
Uncommented mobile clearDirectionsControl div and allowed it to be conditionally rendered within addControl.
Added events within addControl to allow touch/click (depending on platform).
Added class to the created Div as 'maplibregl-ctrl' is required to allow pointer events, as by default all pointer events on the map are disabled, also removed margin as it was making clicks trigger on margin. The 'maplibregl-ctrl' class handles adding a margin without this issue.
- #673
> #673/Added events to MediaMap for clearDirectionsControl.

- backend/backend/urls.py
- backend/entities/serializers.py
---
I split the API documentation (Swagger UI) by the django apps:
- auth
- content
- entities
- events
There is still an overview of all endpoints. 
I thought about splitting it up while manual testing a API endpoint via Swagger UI, it seemed to cluttered to me 😄.
No related issue
> Split API documentation

- frontend/app/spa-loading-template.html
---
Removed scrollbar from loading screen
- #806
> Remove scrollbar from loading screen

- .env.dev
- backend/Dockerfile
- backend/backend/settings.py
- backend/deploy.Dockerfile
---
- Add `CSRF_TRUSTED_ORIGINS` django setting
- Needed in addition to `ALLOWED_HOSTS` so `POST` requests are not blocked ([ref](https://www.reddit.com/r/django/comments/s6daj0/csrf_verification_failed_django_nginx_docker/))
- Add command `python manage.py collectstatic --no-input` already to the `deploy.Dockerfile` so Docker image already has static files prepped 
- :rocket:
> fix(backend): Add 'CSRF_TRUSTED_ORIGINS' django setting

- .github/workflows/owasp_zap_full_scan.yaml
---
Added a GitHub action for OWASP ZAP Full Scan. Tested on my fork.
- #840
> Chore/implement owasp zap GitHub action

- frontend/components/feed/Feed.vue
- frontend/stores/group.ts
- frontend/stores/organization.ts
- frontend/types/entities/organization.d.ts
---
Minor changes to remove the `organization_group` table as we do not need it. All groups have one and only one organization, so we can just have this information in the `group` table.
- No issue
> Remove unneeded organization_group table

- .github/workflows/pr_ci_playwright_e2e.yaml
- frontend/components/header/HeaderWebsite.vue
- frontend/tests/specs/landing-page.spec.ts
---
- `#mobile-header` id was removed in `HeaderWebsite.vue` and caused tests to break, added it back
- added an update to e2e workflow file to attempt solving failing retries
> added the mobile-header id back to fix breaking tests; update workflow

- backend/backend/management/commands/wait_for_db.py
- backend/backend/settings.py
- backend/pyproject.toml
- docker-compose.yml
---
When we spin up docker compose and the database is just a slower than the backend container, we have to restart the container. We solved that with:
```yaml
restart: unless-stopped
```
the restart policy. But I think a custom command that catches the connection error and tries again is the cleaner solution. I would also recommand to keep the restart policy in place. 
To test this, I ran the container and checked the logs.
> added custom management command wait_for_db

- backend/authentication/factories.py
- backend/backend/management/commands/populate_db.py
- docker-compose.yml
---
We have been talking about populating the database with dummy data @andrewtavis @aasimsyed. I have added a custom management command to django `populate_db` with the option to specifiy the number of users via the `--users` flag. 
The file populate_db can be extend to load more dummy data (events, orgs).
> populating the database with dummy data

- frontend/components/modal/ModalSharePage.vue
---
This is the same PR from the other signal additional PR. I have a problem with my git so I had to recreate the branch.
For the implementation, I feel like there is still improvement that can be made, especially with the duplicated copy URL code. Feel free to let me know if there are any ideas/comments.
Also, just an idea, maybe we could add in a "Redirecting to Signal" infobox or something to let the user know that it is redirecting to signal.
- #694
> feat: copy url and redirect to signal when share link is clicked

- CONTRIBUTING.md
- README.md
- backend/authentication/factories.py
- backend/authentication/models.py
- backend/authentication/tests.py
- backend/backend/custom_settings.py
- backend/backend/exception_handler.py
- backend/backend/management/commands/populate_db.py
- backend/backend/settings.py
- backend/backend/tests/unit/conftest.py
- backend/content/factories.py
- backend/content/models.py
- backend/content/serializers.py
- backend/content/tests.py
- backend/entities/factories.py
- backend/entities/models.py
- backend/entities/tests.py
- backend/events/factories.py
- backend/events/models.py
- backend/events/tests.py
- docker-compose.yml
- frontend/components/sidebar/left/SidebarLeft.vue
---
I have added the organizations to the populate db command. 
WIP: 
* org_text needs to be added to the OrganizationFactory
* Events should be added
* Group should be added
- #938
> added orgs to populate db management command, improved org factory

- frontend/components/media/MediaMap.vue
---
Slowly but surely chipping away at some map stuff..
- Was confused by the `keydown` event on `[x]` causing both the clearing of directions and toggling the route profile. Modified so that the route profile is changed instead on `keydown` events on `[p]`. Let me know if there was a reason though for having both actions caused by the same event - wasn't sure
- As per part of the discussion in #961, modified the attribution texts to be more condensed. Went with:
- `© OpenStreetMap` as that is also a fairly common alternative ([ref](https://osmfoundation.org/wiki/Licence/Attribution_Guidelines#Attribution_text)).
- `CyclOSM hosted by OSM France` as opposed to `CyclOSM tiles by OSM France` from https://github.com/activist-org/activist/issues/961#issuecomment-2323958279 , given that I'm …
> refac(map): Update attribution text to condensed version and change profile on key press [p]

- frontend/components/modal/ModalBase.vue
Added if statement to watch(route) so that closeModal() is called only when modals are present.
---
This PR attempts to correct an error that occurs when a user navigates the app and there are no modals in the modal Pinia store. It is part of a larger effort to make the modal implementation more consistent.
- #ISSUE_NUMBER 980
> Bug: 980 (Cannot read properties of undefined (reading 'isOpen') in MediaImageCarousel.vue)

- .pre-commit-config.yaml
- frontend/i18n/check/run_i18n_checks.py
Added centralized script to run all i18n tests and configured pre-commit hook to ensure these tests are run and checks are passed before opening a PR.
---
- #990
> feat: Function to run all i18n tests locally

- frontend/components/dropdown/DropdownTheme.vue
- frontend/components/menu/MenuItemLabel.vue
- frontend/test/components/dropdown/DropdownTheme.spec.ts
---
This fixes a bug where the aria-labels were showing raw translation keys.  Also, the `aria-label` attribute was being set as `arialabel` in menu options causing it not to work.
- #1022
> fix: translations and aria-labels display in theme menu

- frontend/utils/routeUtils.ts
This pull request fixes an issue where the sidebar in SidebarLeftMainSectionSelectors failed to highlight the correct route when localized paths (e.g., /fr, /de) were in use.
Changes Made:
1. Improved the isRouteActive function to handle route prefixes dynamically by stripping localization prefixes before comparing paths.
2. Added support for nested and dynamic routes to ensure consistent behavior across localized and non-localized paths.
Testing:
-Verified functionality manually across multiple localizations (English, French, German) and routes (e.g., organization, event).
This fix ensures that the sidebar accurately highlights the active route, regardless of localization.
> Fix Sidebar Route Highlighting for Localized Routes

- frontend/components/page/PageBreadcrumbs.vue
- frontend/tests/specs/organizationLogic.test.ts
- [] I have not run the tests for the backend and frontend depending on what's needed for my changes as described in the [testing section of the contributing guide](CONTRIBUTING.md#testing)
---
This pull request enhances the route check mechanisms in PageBreadcrumbs.vue by introducing a new organizationRegex to validate routes with the formats /organizations/{UUID} and optionally /organizations/{UUID}/about. This update ensures precise page type determination and improves the logic for fetching organization details by ID from the organizationStore.
Additionally, the regex logic now includes support for the base URL and an optional ISO route. This enhancement makes the implementation more robust by dynamically handling routes depending on the environment (e.g., localhost:3000 for …
> Regex routing for Organization in PageBreadCrumbs.vue

- frontend/utils/routeUtils.ts
This pull request addresses issue #963, where routes were not being handled properly. Previously, isRouteActive assumed a localized route structure. Switching between localized and non-localized routes led to unexpected behavior in terms of resulting pages.
**Changes:**
1. **Locale Stripping Logic:**
Introduced helper functions to strip locale segments from path-based routes and route names. Ensures that core functionality (checking active routes and checking subpages) is stable, regardless of locale prefix. 
2. **Normalized Path Comparisons:**
Updated isRouteActive and related functions to first remove any leading/trailing slashes and locale prefixes before performing comparisons. This makes the logic more resilient to both localized (/en/events) and non-localized (/events) routes. …
>  Fix Routing Logic for Non-Localized Routes and Ensure Robust Locale Handling

- frontend/components/page/PageBreadcrumbs.vue
- [] I have given maintainers the ability to edit this pull request
---
This pull request enhances the route-checking logic in PageBreadcrumbs.vue by introducing robust mechanisms for handling group and event routes.
groupRegex validates routes with the format /organizations/{UUID}/groups/{UUID} and optionally /about. This ensures accurate identification of "group" page types and triggers fetching group details from the groupStore using the fetchById method. This addition enables seamless navigation and dynamic content updates for group-related pages.
eventRegex validates routes with the format …
> added regex logic for groups and events in PageBreadcrumbs.vue

- frontend/utils/routeUtils.ts
This pull request addresses issue #963 .
Description:
This pull request enhances route handling to accommodate both localized and non-localized routes. The core changes include:
Key Changes:
Locale-Agnostic Route Comparison: Introduced removeLocaleFromRouteName to strip locale prefixes from route names. This allows for consistent route comparisons, regardless of the current locale.
Subpage Detection: Updated isCurrentRoutePathSubpageOf to consider locale-stripped route names. This ensures accurate subpage identification, even when switching between locales.
Route Inclusion Check: Modified currentRoutePathIncludes to utilize locale-stripped route names, improving the reliability of route inclusion checks.
Benefits:
Consistent Route Handling: Ensures that route comparisons and subpage …
> Improve Route Handling for Localized and Non-Localized Routes

- frontend/components/SearchBar.vue
- frontend/i18n/check/i18n_check_key_identifiers.py
- frontend/i18n/check/i18n_check_map_object.py
- frontend/i18n/check/i18n_generate_map_object.py
- frontend/i18n/check/run_i18n_checks.py
- frontend/types/i18n-map.ts
---
This PR is the final part of the planned functionality of `i18n-check`, with these commits being added to the [i18n-check](https://github.com/activist-org/i18n-check) repo. Specifically we discussed the potential to load all i18n keys into a generated map object that would then type check all use cases of the keys to make sure that none are misspelled. This is of particular importance for aria labels where the key being misspelled will not be evident to the development team.
Once this is merged a new issue will be opened to switch all keys over to the `i18nMap` object. As of now it's only used in the search bar component for the word `Search`.
- #546
> #546 Base i18n map object and process to create it

- frontend/components/EmptyState.vue
- frontend/components/card/get-involved/CardGetInvolvedOrganization.vue
- frontend/components/card/search-result/CardSearchResult.vue
- frontend/components/combobox/ComboboxTopics.vue
- frontend/components/icon/IconOrganizationStatus.vue
- frontend/components/media/MediaMap.vue
- frontend/components/modal/edit/ModalEditFaqEntry.vue
- frontend/i18n/en-US.json
- frontend/pages/organizations/[id]/groups/index.vue
- frontend/pages/organizations/[id]/resources.vue
- frontend/types/i18n-map.ts
- frontend/utils/groupSubPages.ts
Issue: https://github.com/activist-org/activist/issues/1100
- Migrate all inline i18n keys to use i18nMap object for type-safe references
- Add consistent 'i18n.' namespace prefix to translation keys in:
- EmptyState component buttons
- CardGetInvolvedOrganization links
- CardSearchResult aria labels
- MediaMap control tooltips
- ModalEditFaqEntry text checks
- Group/resource creation pages
- Sidebar navigation labels
- Update HTML title attributes to use translated strings via i18nMap
- Import i18nMap in files where missing (MediaMap, groupSubPages)
- Fix key consistency in discussion input component
--- …
> refactor(i18n): standardize localization key references across components

- CONTRIBUTING.md
- FRONTEND_TESTING.md
- LOCALIZATION.md
---
This adds a guide for writing e2e tests to our documentation.  The focus is on the patterns we are using and why.
- #1049
> Add e2e testing guide

- frontend/test-e2e/accessibility/accessible-names.ts
- frontend/test-e2e/component-objects/InfoMenu.ts
- frontend/test-e2e/component-objects/LanguageMenu.ts
- frontend/test-e2e/component-objects/PasswordStrength.ts
- frontend/test-e2e/component-objects/SidebarLeft.ts
- frontend/test-e2e/component-objects/SidebarRight.ts
- frontend/test-e2e/component-objects/SignInMenu.ts
- frontend/test-e2e/component-objects/ThemeMenu.ts
- frontend/test-e2e/page-objects/SignInPage.ts
- frontend/test-e2e/specs/all/landing-page.spec.ts
- frontend/test-e2e/specs/desktop/landing-page.spec.ts
- frontend/test-e2e/specs/mobile/landing-page.spec.ts
- frontend/utils/i18n.ts
---
This is just renaming the `getI18String` function to `getEnglishText`.  `getEnglishText` more specifically shows what the function does, and follows the pattern of the name `getLocaleText`
> refactor: change getI18String to getEnglishText

- .licenserc.yaml
- frontend/components/card/discussion/CardDiscussionInput.vue
- frontend/components/media/MediaMap.vue
- frontend/components/menu/MenuSubPageSelector.vue
- frontend/types/mention-suggestions.ts
- frontend/utils/mentionSuggestion.ts
---
Refactored mentionSuggestion.js to Typescript and added a types file
When running yarn typecheck, there was a type error when initializing the **popup** variable. I set the type to _Instance_ based on the [tippy.js docs](https://atomiks.github.io/tippyjs/v6/tippy-instance/), but it appears there's still an error.
Please let me know if there's a better way to assign this type! Thank you!
- #1149
> Update mention suggestions to typescript

- .github/workflows/check_dependency_updates.yaml
As said in the issue [comment ](https://github.com/activist-org/activist/issues/1090#issuecomment-2708444053) there was error while running the backend test in workflow `ModuleNotFoundError: No module named 'app'` and also as said in the [1147](https://github.com/activist-org/activist/issues/1147) the typecheck result in the frontend contains too much information and not the TypeErrors.
I have updated the workflow to eliminate the backend error `ModuleNotFoundError: No module named 'app'` it was due to passing the wrong setting file in `DJANGO_SETTINGS_MODULE` and update the frontend test typecheck result to show only the typecheck errors if it exists.
---
- [#1090](https://github.com/activist-org/activist/issues/1090)  [#1147](https://github.com/activist-org/activist/issues/1147)
> fix: frontend and backend test workflow

- .github/workflows/pr_ci_frontend.yaml
- CONTRIBUTING.md
- frontend/test/setup.ts
---
This should fix the issue pointed out in https://github.com/activist-org/activist/pull/1166
Our frontend vitest tests broke recently because a configuration field "locales" was being overwritten causing a typescript error.  This is happening because we have to reload i18n in vitest for our frontend tests to work.
There is an ongoing issue with `@nuxt/test-utils` that makes this necessary because the testing environment has multiple vue app instances in it and doesn't reference them in a consistent manner: https://github.com/nuxt-modules/i18n/issues/2637
This PR changes how i18n is initialized in vitest to get around the typescript error.  This PR also adds the `--silent` flag to running the tests in CI to reduce the amount of Nuxt related warnings that probably need to be resolved in …
> fix: load i18n in tests without typescript error

- backend/content/tests/tests.py
- backend/events/tests.py
---
This test the adds the missing test coverage for 
`backend/content/models.py                            111      8    93%   27, 40, 51, 64, 98, 110, 120, 166` and `backend/events/models.py                              71      1    99%   124`
- [#1134](https://github.com/activist-org/activist/issues/1134)
> Test the __str__ method of different models in backend/content/models.py and backend/events/models.py🧪

- .env.dev
- .gitignore
- backend/authentication/models.py
- backend/communities/groups/models.py
- backend/communities/organizations/models.py
- backend/content/models.py
- backend/content/serializers.py
- backend/content/tests/test_image_upload.py
- backend/core/settings.py
- docker-compose.yml
- frontend/modules.ts
- frontend/nuxt.config.ts
- frontend/package.json
- frontend/yarn.lock
---
This PR addresses the issues presented in #670 .
<ins>Backend</ins>
- Validates image upload file type and content.
- Limits uploaded file size to 5MB.
- Sanitizes uploaded image file names to UUID filenames.
- Scrubs exif data / meta data from jpeg / png format files.
- Uses Pillow. More detailed exif scrubbing is possible through the [piexif](https://pypi.org/project/piexif/) module.
- Adds pytest tests to content/tests/test_image_upload.py to increase test coverage for image upload.
<ins>Frontend</ins>
- Added nuxt-security module and set up first iteration of config.
- This provides header- and middleware-based protection against OWASP Top Ten threats, as well as:
- Image file source / location restriction as part of broader Content Security Policy.
- Rate limiting.
- Upload file …
>  Issue 670. Image Upload Validation.

- backend/authentication/tests.py
- backend/communities/groups/tests/test_group.py
- backend/communities/groups/tests/test_group_events.py
- backend/communities/groups/tests/test_group_image.py
- backend/communities/groups/tests/test_group_member.py
- backend/communities/groups/tests/test_group_resource.py
- backend/communities/groups/tests/test_group_text.py
- backend/communities/groups/tests/test_group_topic.py
- backend/communities/organizations/tests/test_org_events.py
- backend/communities/organizations/tests/test_org_member.py
- backend/communities/organizations/tests/test_org_resource.py
- backend/communities/organizations/tests/test_org_text.py
- backend/communities/organizations/tests/test_org_topic.py
- backend/communities/tests.py
> Missing test for deleting authenticated users

- frontend/nuxt.config.ts
Nuxt-security module provides cors protection for Nitro server. Cors is not needed here, so it is disabled.
---
This PR resolves the uncertainty about the Access-Control-Allow-Origin header that appeared after installing the nuxt-security module. It was not clear why this header was made available.
This setting is intended to configure the Nitro server (which Nuxt uses) for cross-origin connections. Since we don't anticipate cross-origin connections at the present time, cors headers are disabled.
- #1172
> 1172 - Disable CORS setting (Access-Control-Allow-Origin).

- frontend/nuxt.config.ts
- frontend/package.json
- frontend/yarn.lock
---
Removes the `upgrade-insecure-requests` in local dev environments.  This allows playwright's webkit based browsers to make http requests when running playwright locally, as well as developers using safari locally.
- #1186
> fix: remove upgrade-insecure-requests header in local dev

- frontend/app.vue
- frontend/components/card/CardConnect.vue
- frontend/components/card/CardDetails.vue
- frontend/components/card/about/CardAboutEvent.vue
- frontend/components/card/about/CardAboutGroup.vue
- frontend/components/card/about/CardAboutOrganization.vue
- frontend/components/card/get-involved/CardGetInvolvedEvent.vue
- frontend/components/card/get-involved/CardGetInvolvedGroup.vue
- frontend/components/card/get-involved/CardGetInvolvedOrganization.vue
- frontend/components/media/image-carousel/MediaImageCarousel.vue
- frontend/components/media/image-carousel/MediaImageCarouselFull.vue
- frontend/components/modal/edit/ModalEditSocialLinks.vue
- frontend/components/modal/edit/text/ModalEditTextEvent.vue
- frontend/components/modal/edit/text/ModalEditTextGroup.vue
- frontend/components/modal/edit/text/ModalEditTextOrganization.vue
- frontend/pages/organizations/[orgId]/about.vue
---
This PR removes duplicate import statements across multiple components to improve code clarity and maintainability. The affected files had redundant type imports and composables, which have now been cleaned up.
- #1189
> refactor: remove unused useModalHandlers imports from various components

- .github/workflows/pr_ci_backend.yaml
- .github/workflows/pr_ci_frontend.yaml
- backend/authentication/admin.py
- backend/core/management/commands/wait_for_db.py
- backend/pyproject.toml
---
This pull request resolves the` **mypy**` type checking errors in multiple backend files. These errors were related to incorrect use of type annotations, particularly in the imports and the UserAdmin class. The fixes align the codebase with proper type checking and ensure that the backend is compliant with Python's typing standards.
- see the issue [here ](https://github.com/activist-org/activist/issues/1190)
> Fix mypy Type Errors in Backend Files (#1190)

- backend/authentication/tests/__init__.py
- backend/authentication/tests/test_auth.py
- backend/authentication/tests/test_serializers.py
PFA 
---
This pull request improves test coverage in `backend/authentication/serializers.py`, specifically addressing the missing lines **111-114** in the `PasswordResetSerializer`. I have added test cases to ensure these lines are covered.  
Changes :
Refactored the `tests/` folder, organizing them into separate files:
`test_auth.py`
`test_serializer.py`
Updated `DeleteUserResponseSerializer`, `SignupSerializer`, `LoginSerializer`, and `PasswordResetSerializer` for consistency and 100% test coverage, following the DRF serializer testing pattern.
Testing :
- Verified that all tests pass successfully.  
I followed [this resource](https://www.vintasoftware.com/blog/how-i-test-my-drf-serializers), as suggested by @andrewtavis, to refine the test implementation for DRF serializers.  
- #1133
> #Issue1133 : Serializers tests for Authentication 

- backend/pyproject.toml
---
This pull request contains config to exclude  `__str__` or `meta class` from numpy doc validation. After adding the config
`__str__` warning were suppressed. I have also added the config for meta and `__init__`
Backend/pyproject.toml
I have done the backend testing Attached are the result
[Issue 1198](https://github.com/activist-org/activist/issues/1198)
> Doc: Exclude str method and meta class from numpy doc validation

- backend/utils/tests/test_utils.py
---
This PR adds unit tests for the utils.py file while keeping the existing patterns intact. The utils.py file now has 100% test coverage.
```
content/serializers.py                        78     14    82%   86-91, 113-115, 148, 261-275
content/urls.py                               10      0   100%
content/views.py                             163    111    32%   35-43, 49-60, 63-73, 76-86, 89-100, 103-112, 125-133, 139-150, 153-156, 159-170, 173-184, 187-196, 208-215, …
```
> added unit tests for the utils.py file

- frontend/layouts/event/EventList.vue
- frontend/layouts/event/EventPage.vue
- frontend/layouts/group/GroupPage.vue
- frontend/layouts/organization/OrganizationList.vue
- frontend/layouts/organization/OrganizationPage.vue
- frontend/pages/events/[eventId]/about.vue
- frontend/pages/events/[eventId]/discussion.vue
- frontend/pages/events/[eventId]/index.vue
- frontend/pages/events/[eventId]/resources.vue
- frontend/pages/events/[eventId]/settings.vue
- frontend/pages/events/[eventId]/tasks.vue
- frontend/pages/events/[eventId]/team.vue
- frontend/pages/events/index.vue
- frontend/pages/groups/index.vue
- frontend/pages/organizations/[orgId]/about.vue
- frontend/pages/organizations/[orgId]/affiliates.vue
- frontend/pages/organizations/[orgId]/application.vue
- frontend/pages/organizations/[orgId]/events.vue
- frontend/pages/organizations/[orgId]/faq.vue
- frontend/pages/organizations/[orgId]/groups/[groupId]/about.vue
- frontend/pages/organizations/[orgId]/groups/[groupId]/events.vue
- frontend/pages/organizations/[orgId]/groups/[groupId]/faq.vue
- frontend/pages/organizations/[orgId]/groups/[groupId]/resources.vue
- frontend/pages/organizations/[orgId]/groups/index.vue
- frontend/pages/organizations/[orgId]/index.vue
- frontend/pages/organizations/[orgId]/resources.vue
- frontend/pages/organizations/[orgId]/settings.vue
- frontend/pages/organizations/[orgId]/tasks.vue
- frontend/pages/organizations/[orgId]/team.vue
- frontend/pages/organizations/index.vue
---
This is the first step in migrating the platform to just do API calls from the layouts. All layouts have had appropriate API calls added to them, the layouts have been dynamically assigned (in a prior commit) and all pages now load in the given object via props from `NuxtPage` within the layout.
Further steps needed:
- Convert all components to just access objects from pages
- Make layouts distinct given their functionality such that the left sidebar isn't conditionally rendering, but rather rendering for the page type
- #1060
> #1060 API calls in layouts and remove all page calls

- .github/workflows/check_dependency_updates.yaml
When a bot creates an issue mentioning what are the latest dependencies version that our project will need to be updated, the date in the issue title title was showing `$(date '+%B %d, %Y'` instead of real date, so this PR aims to fix that.
---
- [#1262](https://github.com/activist-org/activist/issues/1262)
> fix: Issue in report title is not showing

- backend/core/tests/unit/conftest.py
- backend/core/tests/unit/test_throttling.py
---
This PR introduces a pytest fixture that disables throttling by default for all tests, improving test performance and developer experience. Throttling can still be enabled for specific tests by marking them with @pytest.mark.enable_throttling.
Additionally, I added dedicated throttling tests for both anonymous and authenticated users, with the appropriate marker applied to ensure throttling is tested as expected.
I initially explored PR #1229 to build on that work, but the branch hadn't been updated in a while and I ran into issues running it locally. To make things easier to test, I opened this new PR with a fresh implementation.
- #879
> throttling setup for tests, throttling tests for anon and user

- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultEvent.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultGroup.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultOrganization.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultResource.vue
- frontend/components/tooltip/menu-search-result/TooltipMenuSearchResultUser.vue
- frontend/pages/auth/sign-up.vue
- frontend/pages/events/[eventId]/about.vue
- frontend/pages/organizations/[orgId]/about.vue
- frontend/pages/organizations/[orgId]/groups/[groupId]/about.vue
- frontend/pages/organizations/create.vue
- frontend/test-e2e/page-objects/SignInPage.ts
- frontend/test-e2e/specs/desktop/events-page.spec.ts
- frontend/test-e2e/specs/mobile/events-page.spec.ts
---
Various changes within this PR:
- Fixes the e2e tests via the new form components
- Share icons were all moved over to the right
- The submit button for organization creation had a left margin that was removed
- #841
> #841 Fix e2e tests for sign in and event page + update share icon location + org create styling

- .pre-commit-config.yaml
- pre_commit_scripts/prettier_eslint_checks.py
- Refactored import in prettier_eslint_checks.py to use relative import: from .utils import run_shell_command
- Updated pre-commit hook to run the script as a module using python -m
- Fixes mypy static type checking error caused by incorrect import resolution
- Ensures cross-platform compatibility with tools like pre-commit (Windows/Linux/macOS)
Closes #1344
> Refactor module import and pre-commit hook execution to fix mypy error

- README.md
- STYLEGUIDE.md
---
This PR adds a new section to the style guide under the name Text styles, explaining how global typography is handled using semantic HTML tags (h1, h2, p, etc.) with Tailwind classes applied at the component level. This addition aims to encourage consistent use of predefined styles rather than applying utility classes individually on each element.
It also introduces a subsection for Text Colors, documenting semantic utility classes like distinct-text, link-text, error-text, and warn-text.
- #1341
> chore:update styleguide with new text stying guide section

- FRONTEND_TESTING.md
- backend/core/management/commands/populate_db.py
- frontend/components/dropdown/DropdownTheme.vue
- frontend/components/events/EventsCalendar.vue
- frontend/components/media/MediaCalendar.vue
- frontend/components/media/map/MediaMapEvent.vue
- frontend/components/media/map/MediaMapEvents.vue
- frontend/composables/useColor.ts
- frontend/composables/useColorModeImages.ts
- frontend/composables/useMap.ts
- frontend/pages/events/index.vue
- frontend/test/composables/useColor.spec.ts
- frontend/types/color.ts
- frontend/utils/utils.ts
---
Adding a popover slot for each day so consumers can inject custom content when a day is clicked or hovered.
Introducing new props for passing event data into the calendar, enabling more flexible and contextual rendering.
Creating a dedicated calendar view for events, allowing users to visualize and interact with event data directly in the calendar UI.
- Closes #1389
> 1389 calendar events view

- frontend/components/form/Form.vue
- frontend/components/form/text/FormTextInputPassword.vue
Fix password visibility issue in login form by adding `type="button"` to the password toggle button.
- Add `type="button"` attribute to prevent form submission when clicking eye icon
- Fixes password briefly showing when pressing Enter to submit form
- Fixes #1400
- Supersedes #1404 (previous attempt with dependency conflicts)
> Fix password visibility issue in login form

- frontend/components/card/CardMetricsOverview.vue
- frontend/components/menu/MenuItemLabel.vue
- Added 'dark:group-hover:fill-cta-orange' class to Icon component in MenuItemLabel.vue
- Icons now change color simultaneously with text on hover in dark mode
- Fixes issue where icons required mouse movement to trigger color change
Fixes #1401
> fix: sidebar menu option icons not receiving CSS group hover actions

- backend/authentication/models.py
- backend/authentication/serializers.py
- backend/authentication/tests/test_auth.py
- backend/authentication/views.py
- backend/content/serializers.py
- backend/utils/utils.py
- frontend/utils/sidebarUtils.ts
---
Removes three fields from the user model in the backend as they're in the default `AbstractUser` class that we use from Django. Fixed the test for sign up as that was passing a name rather than a username, which was accepted by our original custom field, but not by the default (we were accepting spaces for a full name as a username). Also includes a minor frontend fix from a refactor I did.
Will merge when tests pass :)
- #682
> #682 Update user model in backend to not recreate default field

- backend/content/tests/faq/test_faq.py
- backend/content/tests/social_link/test_social_link.py
- backend/events/tests/resource/test_resource_serializer.py
---
- #1133
Previously, the events serializers test coverage was at 73%. After adding new tests, I’ve increased it to 90%
> TEST: Added tests for  events serializers

- CONTRIBUTING.md
---
The CONTRIBUTING.md file was missing database population commands for local Python backend setup (non-Docker).
Added the missing `loaddata` and `populate_db` commands to complete the local development setup instructions.
Suggested in Matrix development group chat.
There are no related issues, this fix came from a suggestion in the development chata
> docs: update local backend setup commands in CONTRIBUTING.md

- frontend/components/sidebar/left/content/SidebarLeftContentEvent.vue
- frontend/components/sidebar/left/content/SidebarLeftContentGroupPage.vue
- frontend/components/sidebar/left/content/SidebarLeftContentOrganization.vue
- Replace ariaLabel prop with :aria-label attribute on native <button> elements
- Use $t() function to translate i18n keys for proper screen reader support
- Fix 3 sidebar components: Organization, GroupPage, and Event
- Ensures screen readers receive translated text instead of literal i18n keys
Components fixed:
- SidebarLeftContentOrganization.vue
- SidebarLeftContentGroupPage.vue
- SidebarLeftContentEvent.vue
Example of change:
```vue
<button
v-if="
showButton &&
(sidebar.collapsed == false || sidebar.collapsedSwitch == false)
"
@click="openModal()"
class="focus-brand absolute bottom-1 right-1 z-10 flex rounded-md border border-black/80 bg-white/80 p-1 text-black/80 dark:border-white/80 dark:bg-black/80 dark:text-white/80"
ariaLabel="i18n.components.sidebar_left_content_organization.edi …
```
> fix(accessibility): use :aria-label attribute for native HTML buttons
